import type { SkillContent } from "./contentTypes";

/**
 * Grammar levels 1-4.
 *
 * Every level follows the same shape: 3 sub-lessons with representative names,
 * each one with its own bank of 4-5 exercises. Every exercise carries an
 * explicit `instruction`, a `hint` that removes ambiguity, and an
 * `explanation` used by the feedback panel, so only one answer can be read as
 * correct.
 */
export const GRAMMAR_LEVELS_1_TO_4: SkillContent = {
  "basic-greetings": {
    lessonTopics: [
      {
        id: "basic-greetings-hello",
        label: "Saying Hello",
        state: "active",
        marker: "1",
        levelText: "LEVEL 1 · LESSON 1",
        title: "Greetings — Saying Hello",
        description:
          "Greet other people at any time of the day. In English the greeting always comes first, before your name or any question.",
        objectives: [
          "Recognize the most common greetings",
          "Choose a greeting for morning, afternoon and evening",
          "Answer a greeting politely",
        ],
        formulaLabel: "Greeting + (name)",
        formula: "Hello / Hi / Good morning + name",
        examples: [
          { source: "Hello, Ana.", translation: "Hola, Ana." },
          { source: "Good morning, Mr. Lopez.", translation: "Buenos dias, Sr. Lopez." },
          { source: "Good evening!", translation: "Buenas noches (al llegar)." },
        ],
        xpReward: 34,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "bg-l1-e1",
            type: "choice",
            instruction: "Choose the greeting that completes the sentence.",
            hint: "Only one option is a greeting; the other two are a verb and a color.",
            prompt: "_____ , my name is Sara.",
            options: ["Hello", "Run", "Blue"],
            correctAnswer: "Hello",
            explanation: "\"Hello\" is the only greeting. \"Run\" is a verb and \"blue\" is a color.",
            translation: "Hola, mi nombre es Sara.",
          },
          {
            id: "bg-l1-e2",
            type: "choice",
            instruction: "Choose the correct greeting for 8:00 in the morning.",
            hint: "English uses a different greeting for each part of the day: morning, afternoon and evening.",
            prompt: "It is 8:00 a.m. You say: _____ !",
            options: ["Good morning", "Good afternoon", "Good night"],
            correctAnswer: "Good morning",
            explanation: "\"Good morning\" is used until midday. \"Good night\" is only used to say goodbye before sleeping.",
            translation: "Buenos dias.",
          },
          {
            id: "bg-l1-e3",
            type: "input",
            instruction: "Write the missing greeting word.",
            hint: "Write ONE word only: the informal greeting of two letters used with friends.",
            prompt: "_____ , Luis! How are you?",
            answerLabel: "Write one greeting word:",
            expectedFormat: "One word. Capital letters and punctuation are not graded.",
            placeholder: "one word...",
            correctAnswer: "hi",
            acceptedAnswers: ["hi", "hello"],
            explanation: "\"Hi\" is the short informal greeting. \"Hello\" is also accepted because it works in the same position.",
            translation: "Hola, Luis. Como estas?",
          },
          {
            id: "bg-l1-e4",
            type: "choice",
            instruction: "Choose the polite answer to the greeting.",
            hint: "Answer the greeting first and then say how you are. Only one option does both.",
            prompt: "A: Good afternoon! B: _____",
            options: ["Good afternoon! I'm fine, thanks.", "Yes, please.", "My name is a teacher."],
            correctAnswer: "Good afternoon! I'm fine, thanks.",
            explanation: "A greeting is answered with a greeting. \"Yes, please\" answers an offer, and the third option is not correct English.",
            translation: "Buenas tardes. Estoy bien, gracias.",
          },
        ],
      },
      {
        id: "basic-greetings-introduce",
        label: "Introducing Yourself",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 1 · LESSON 2",
        title: "Greetings — Introducing Yourself",
        description:
          "Say who you are with two fixed patterns: \"I'm + name\" and \"My name is + name\". Both are correct, but they never mix.",
        objectives: [
          "Introduce yourself with I'm + name",
          "Introduce yourself with My name is + name",
          "Avoid mixing both patterns in one sentence",
        ],
        formulaLabel: "I'm + name / My name is + name",
        formula: "I'm Ana. = My name is Ana.",
        examples: [
          { source: "Hello, I'm Ana.", translation: "Hola, soy Ana." },
          { source: "Hi, my name is Luis.", translation: "Hola, mi nombre es Luis." },
          { source: "I'm Mateo, from Quito.", translation: "Soy Mateo, de Quito." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "bg-l2-e1",
            type: "input",
            instruction: "Complete the introduction with the missing name.",
            hint: "Copy the name that appears in the Spanish translation below. Write only the name.",
            prompt: "Hi, I am _____ .",
            answerLabel: "Write the name only:",
            expectedFormat: "One word (a name). Capital letters are not graded.",
            placeholder: "a name...",
            correctAnswer: "ana",
            explanation: "The translation says \"soy Ana\", so the missing word is the name Ana.",
            translation: "Hola, soy Ana.",
          },
          {
            id: "bg-l2-e2",
            type: "choice",
            instruction: "Choose the correct introduction.",
            hint: "\"I'm\" and \"My name is\" are two complete patterns; using both together is wrong.",
            prompt: "Which sentence is correct English?",
            options: ["My name is Luis.", "My name I'm Luis.", "I'm name Luis."],
            correctAnswer: "My name is Luis.",
            explanation: "\"My name is + name\" is the complete pattern. The other options mix two patterns in one sentence.",
            translation: "Mi nombre es Luis.",
          },
          {
            id: "bg-l2-e3",
            type: "input",
            instruction: "Write the missing verb of the introduction.",
            hint: "Write ONE word: the verb that goes after \"I\". Do not write the name.",
            prompt: "Hello! I _____ Carla.",
            answerLabel: "Write the missing verb:",
            expectedFormat: "One word. The contraction \"'m\" is also accepted.",
            placeholder: "one verb...",
            correctAnswer: "am",
            acceptedAnswers: ["am", "'m", "m"],
            explanation: "With the subject \"I\" the verb to be is always \"am\": I am Carla / I'm Carla.",
            translation: "Hola, soy Carla.",
          },
          {
            id: "bg-l2-e4",
            type: "reorder",
            instruction: "Build the introduction using every word once.",
            hint: "Order: greeting first, then the subject, then the verb, then the name. Tap the words in that order.",
            prompt: "Hello / Ana / I'm",
            options: ["Hello", "I'm", "Ana"],
            correctAnswer: "hello i'm ana",
            explanation: "English puts the greeting first and then the introduction: Hello, I'm Ana.",
            translation: "Hola, soy Ana.",
          },
        ],
      },
      {
        id: "basic-greetings-asking",
        label: "Asking Someone's Name",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 1 · LESSON 3",
        title: "Greetings — Asking Someone's Name",
        description:
          "Ask for someone's name and close the introduction politely with \"Nice to meet you\".",
        objectives: [
          "Ask What's your name?",
          "Answer with your own name",
          "Close an introduction politely",
        ],
        formulaLabel: "What's your name? + Nice to meet you.",
        formula: "What's your name? / I'm ... / Nice to meet you.",
        examples: [
          { source: "What's your name?", translation: "Como te llamas?" },
          { source: "Nice to meet you.", translation: "Mucho gusto." },
          { source: "Nice to meet you too.", translation: "Mucho gusto tambien." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "bg-l3-e1",
            type: "choice",
            instruction: "Choose the question that asks for a name.",
            hint: "Look at the question word. Only one of them asks for a name; the others ask about place and manner.",
            prompt: "You want to know a person's name. You ask:",
            options: ["What's your name?", "Where are you?", "How are you?"],
            correctAnswer: "What's your name?",
            explanation: "\"What\" asks for information about a thing or a name. \"Where\" asks for a place and \"How\" asks about state.",
            translation: "Como te llamas?",
          },
          {
            id: "bg-l3-e2",
            type: "input",
            instruction: "Write the missing question word.",
            hint: "Write ONE word: the question word used to ask for a name.",
            prompt: "_____ is your name?",
            answerLabel: "Write the question word:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one question word...",
            correctAnswer: "what",
            explanation: "Names are asked with \"What\": What is your name? (What's your name?)",
            translation: "Cual es tu nombre?",
          },
          {
            id: "bg-l3-e3",
            type: "reorder",
            instruction: "Build the polite closing sentence using every word once.",
            hint: "The fixed English expression has four words and starts with the adjective \"Nice\".",
            prompt: "you / to / Nice / meet",
            options: ["Nice", "to", "meet", "you"],
            correctAnswer: "nice to meet you",
            explanation: "\"Nice to meet you\" is a fixed expression: the word order never changes.",
            translation: "Mucho gusto.",
          },
          {
            id: "bg-l3-e4",
            type: "choice",
            instruction: "Choose the correct answer to \"Nice to meet you.\"",
            hint: "The person is returning the same idea. Only one option does that in correct English.",
            prompt: "A: Nice to meet you. B: _____",
            options: ["Nice to meet you too.", "Yes, I am Ana.", "Good night."],
            correctAnswer: "Nice to meet you too.",
            explanation: "\"too\" returns the same idea. The other options do not answer the expression.",
            translation: "Mucho gusto tambien.",
          },
        ],
      },
    ],
  },

  "simple-present": {
    lessonTopics: [
      {
        id: "simple-present-affirmative",
        label: "Affirmative Sentences",
        state: "active",
        marker: "1",
        levelText: "LEVEL 2 · LESSON 1",
        title: "Simple Present — Affirmative",
        description:
          "Talk about routines and habits with I, you, we and they. With these subjects the verb keeps its base form.",
        objectives: [
          "Use the base form of the verb with I, you, we, they",
          "Build affirmative sentences about routines",
          "Recognize time expressions like every day",
        ],
        formulaLabel: "Subject + base verb",
        formula: "I work / They study",
        examples: [
          { source: "I work every day.", translation: "Trabajo todos los dias." },
          { source: "They study English.", translation: "Ellos estudian ingles." },
          { source: "We live in Quito.", translation: "Vivimos en Quito." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sp-l1-e1",
            type: "choice",
            instruction: "Choose the correct verb form for the subject \"They\".",
            hint: "With I, you, we and they the verb never takes -s and is never in -ing here.",
            prompt: "They _____ at school every day.",
            options: ["works", "work", "working"],
            correctAnswer: "work",
            explanation: "\"They\" is plural, so the verb stays in its base form: work. \"Works\" is only for he/she/it.",
            translation: "Ellos trabajan en la escuela todos los dias.",
          },
          {
            id: "sp-l1-e2",
            type: "input",
            instruction: "Write the verb \"live\" in the correct form for \"I\".",
            hint: "Write ONE word. With \"I\" the simple present uses the base form, with no -s and no -ing.",
            prompt: "I _____ in Quito.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word, base form.",
            placeholder: "one verb...",
            correctAnswer: "live",
            explanation: "With \"I\" the verb stays in the base form: I live. \"Lives\" would need he/she/it.",
            translation: "Vivo en Quito.",
          },
          {
            id: "sp-l1-e3",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "English order is subject + verb + complement. Start with the subject \"We\".",
            prompt: "English / We / study",
            options: ["We", "study", "English"],
            correctAnswer: "we study english",
            explanation: "The subject comes first, then the verb, then the object: We study English.",
            translation: "Nosotros estudiamos ingles.",
          },
          {
            id: "sp-l1-e4",
            type: "choice",
            instruction: "Choose the sentence that describes a daily routine.",
            hint: "A routine uses the simple present, not the -ing form.",
            prompt: "Which sentence talks about a habit that repeats every day?",
            options: ["I read the news every morning.", "I am reading the news now.", "I read the news yesterday."],
            correctAnswer: "I read the news every morning.",
            explanation: "\"Every morning\" marks a routine, so the simple present is used. The second sentence is happening now and the third one is past.",
            translation: "Leo las noticias cada manana.",
          },
        ],
      },
      {
        id: "simple-present-third-person",
        label: "Third Person -s",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 2 · LESSON 2",
        title: "Simple Present — Third Person -s",
        description:
          "With he, she and it the verb takes -s (or -es / -ies). This is the most common mistake at this level.",
        objectives: [
          "Add -s to the verb with he, she, it",
          "Use -es after ch, sh, ss, x and o",
          "Change y to ies after a consonant",
        ],
        formulaLabel: "He/She/It + verb + s",
        formula: "She works / He watches / It studies",
        examples: [
          { source: "She studies every day.", translation: "Ella estudia todos los dias." },
          { source: "He watches TV at night.", translation: "El ve television en la noche." },
          { source: "It goes fast.", translation: "Va rapido." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sp-l2-e1",
            type: "input",
            instruction: "Write the verb \"study\" in the correct form for \"She\".",
            hint: "Write ONE word. The verb ends in consonant + y, so y changes to ies.",
            prompt: "She _____ English every morning.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word, third person form.",
            placeholder: "one verb...",
            correctAnswer: "studies",
            explanation: "After a consonant, final y becomes ies: study -> studies. \"Studys\" does not exist.",
            translation: "Ella estudia ingles cada manana.",
          },
          {
            id: "sp-l2-e2",
            type: "choice",
            instruction: "Choose the correct third person form of \"watch\".",
            hint: "Verbs ending in ch take -es, not just -s.",
            prompt: "He _____ TV after dinner.",
            options: ["watchs", "watches", "watch"],
            correctAnswer: "watches",
            explanation: "Verbs ending in ch, sh, ss, x or o add -es: watch -> watches.",
            translation: "El ve television despues de la cena.",
          },
          {
            id: "sp-l2-e3",
            type: "input",
            instruction: "Write the verb \"go\" in the correct form for \"My brother\".",
            hint: "Write ONE word. \"My brother\" works like \"he\", and verbs ending in o add -es.",
            prompt: "My brother _____ to the gym on Mondays.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word, third person form.",
            placeholder: "one verb...",
            correctAnswer: "goes",
            explanation: "\"My brother\" = he, and go ends in o, so it takes -es: goes.",
            translation: "Mi hermano va al gimnasio los lunes.",
          },
          {
            id: "sp-l2-e4",
            type: "choice",
            instruction: "Choose the sentence with the correct third person form.",
            hint: "Check which subject is he/she/it: only that subject takes the -s.",
            prompt: "Which sentence is correct?",
            options: ["Ana live in Guayaquil.", "Ana lives in Guayaquil.", "Ana livees in Guayaquil."],
            correctAnswer: "Ana lives in Guayaquil.",
            explanation: "\"Ana\" is a third person singular subject, so the verb takes -s: lives.",
            translation: "Ana vive en Guayaquil.",
          },
        ],
      },
      {
        id: "simple-present-negative-questions",
        label: "Negatives and Questions",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 2 · LESSON 3",
        title: "Simple Present — Negatives and Questions",
        description:
          "Use the auxiliary do / does to make negatives and questions. After the auxiliary the main verb always returns to its base form.",
        objectives: [
          "Form negatives with don't / doesn't",
          "Form questions with Do / Does",
          "Keep the main verb in base form after the auxiliary",
        ],
        formulaLabel: "Subject + don't/doesn't + base verb",
        formula: "I don't work / Does she work?",
        examples: [
          { source: "I don't work on Sundays.", translation: "No trabajo los domingos." },
          { source: "She doesn't like coffee.", translation: "A ella no le gusta el cafe." },
          { source: "Do you speak English?", translation: "Hablas ingles?" },
        ],
        xpReward: 50,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "sp-l3-e1",
            type: "choice",
            instruction: "Choose the correct negative auxiliary for \"She\".",
            hint: "With he, she and it the auxiliary carries the -s, so the main verb loses it.",
            prompt: "She _____ like coffee.",
            options: ["don't", "doesn't", "isn't"],
            correctAnswer: "doesn't",
            explanation: "Third person singular uses doesn't + base verb. \"Isn't\" belongs to the verb to be, not to \"like\".",
            translation: "A ella no le gusta el cafe.",
          },
          {
            id: "sp-l3-e2",
            type: "input",
            instruction: "Write the missing negative auxiliary for \"I\".",
            hint: "Write ONE word: the contraction of do + not.",
            prompt: "I _____ work on Sundays.",
            answerLabel: "Write the auxiliary:",
            expectedFormat: "One word. \"do not\" is also accepted.",
            placeholder: "one auxiliary...",
            correctAnswer: "don't",
            acceptedAnswers: ["don't", "dont", "do not"],
            explanation: "With I, you, we and they the negative is don't (do not) + base verb.",
            translation: "No trabajo los domingos.",
          },
          {
            id: "sp-l3-e3",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "A simple present question starts with the auxiliary Do, then the subject, then the base verb.",
            prompt: "you / Do / English / speak",
            options: ["Do", "you", "speak", "English"],
            correctAnswer: "do you speak english",
            explanation: "Questions put the auxiliary first: Do + subject + base verb.",
            translation: "Hablas ingles?",
          },
          {
            id: "sp-l3-e4",
            type: "choice",
            instruction: "Choose the correct question form.",
            hint: "After Does the main verb never keeps the -s: the auxiliary already carries it.",
            prompt: "_____ he live in Cuenca?",
            options: ["Do", "Does", "Is"],
            correctAnswer: "Does",
            explanation: "With he/she/it the question auxiliary is Does + base verb: Does he live...?",
            translation: "Vive el en Cuenca?",
          },
        ],
      },
    ],
  },

  pronouns: {
    lessonTopics: [
      {
        id: "pronouns-subject",
        label: "Subject Pronouns",
        state: "active",
        marker: "1",
        levelText: "LEVEL 3 · LESSON 1",
        title: "Pronouns — Subject Pronouns",
        description:
          "Replace the person or thing that does the action: I, you, he, she, it, we, they. The subject pronoun always goes before the verb.",
        objectives: [
          "Identify the seven subject pronouns",
          "Match a name with its pronoun",
          "Use the pronoun before the verb",
        ],
        formulaLabel: "Noun -> Pronoun",
        formula: "Ana -> she / Carlos -> he",
        examples: [
          { source: "Ana is a doctor. She is kind.", translation: "Ana es doctora. Ella es amable." },
          { source: "Carlos is late. He is running.", translation: "Carlos llega tarde. El esta corriendo." },
          { source: "The book is new. It is blue.", translation: "El libro es nuevo. Es azul." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "pr-l1-e1",
            type: "choice",
            instruction: "Choose the pronoun that replaces \"Carlos\".",
            hint: "Carlos is one man, so you need the masculine singular pronoun.",
            prompt: "Carlos is tired. _____ needs a break.",
            options: ["He", "She", "It"],
            correctAnswer: "He",
            explanation: "\"He\" replaces one man. \"She\" is for a woman and \"it\" for things or animals.",
            translation: "Carlos esta cansado. El necesita un descanso.",
          },
          {
            id: "pr-l1-e2",
            type: "input",
            instruction: "Write the pronoun that replaces \"Ana and I\".",
            hint: "Write ONE word. The group includes you, so use the first person plural pronoun.",
            prompt: "Ana and I are students. _____ study every day.",
            answerLabel: "Write the pronoun:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one pronoun...",
            correctAnswer: "we",
            explanation: "\"Ana and I\" includes the speaker, so the pronoun is \"we\".",
            translation: "Ana y yo somos estudiantes. Nosotros estudiamos todos los dias.",
          },
          {
            id: "pr-l1-e3",
            type: "choice",
            instruction: "Choose the pronoun that replaces \"the keys\".",
            hint: "The keys are more than one thing, and things use the same plural pronoun as people.",
            prompt: "The keys are on the table. _____ are mine.",
            options: ["It", "They", "He"],
            correctAnswer: "They",
            explanation: "Plural nouns, including things, are replaced by \"they\". \"It\" is only for one thing.",
            translation: "Las llaves estan en la mesa. Son mias.",
          },
          {
            id: "pr-l1-e4",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "Put the subject pronoun first, then the verb, then the complement.",
            prompt: "my teacher / She / is",
            options: ["She", "is", "my teacher"],
            correctAnswer: "she is my teacher",
            explanation: "The subject pronoun starts the sentence: She is my teacher.",
            translation: "Ella es mi profesora.",
          },
        ],
      },
      {
        id: "pronouns-object",
        label: "Object Pronouns",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 3 · LESSON 2",
        title: "Pronouns — Object Pronouns",
        description:
          "Replace the person or thing that receives the action: me, you, him, her, it, us, them. The object pronoun goes after the verb or after a preposition.",
        objectives: [
          "Identify the object pronouns",
          "Place the object pronoun after the verb",
          "Contrast subject and object pronouns",
        ],
        formulaLabel: "Verb + object pronoun",
        formula: "I call him / She helps us",
        examples: [
          { source: "I call him every night.", translation: "Lo llamo cada noche." },
          { source: "She helps us with homework.", translation: "Ella nos ayuda con la tarea." },
          { source: "Please give it to me.", translation: "Por favor damelo." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "pr-l2-e1",
            type: "choice",
            instruction: "Choose the object pronoun that replaces \"Maria\".",
            hint: "The pronoun comes after the verb, so it must be an object pronoun, not \"she\".",
            prompt: "I saw Maria yesterday. I saw _____ at the library.",
            options: ["she", "her", "hers"],
            correctAnswer: "her",
            explanation: "After the verb we use the object pronoun \"her\". \"She\" is a subject pronoun and \"hers\" is a possessive.",
            translation: "Vi a Maria ayer. La vi en la biblioteca.",
          },
          {
            id: "pr-l2-e2",
            type: "input",
            instruction: "Write the object pronoun that refers to the speaker.",
            hint: "Write ONE word: the object form of \"I\".",
            prompt: "Can you help _____ , please?",
            answerLabel: "Write the object pronoun:",
            expectedFormat: "One word.",
            placeholder: "one pronoun...",
            correctAnswer: "me",
            explanation: "The object form of \"I\" is \"me\": Can you help me?",
            translation: "Puedes ayudarme, por favor?",
          },
          {
            id: "pr-l2-e3",
            type: "choice",
            instruction: "Choose the sentence with the correct object pronoun.",
            hint: "After the verb \"call\" you need an object pronoun, not a subject pronoun.",
            prompt: "Which sentence is correct?",
            options: ["I call they every Sunday.", "I call them every Sunday.", "I call their every Sunday."],
            correctAnswer: "I call them every Sunday.",
            explanation: "\"Them\" is the object form of \"they\". \"Their\" is a possessive adjective.",
            translation: "Los llamo todos los domingos.",
          },
          {
            id: "pr-l2-e4",
            type: "input",
            instruction: "Write the object pronoun that replaces \"my brother\".",
            hint: "Write ONE word: the object form used for one man.",
            prompt: "My brother is sick. I visit _____ every afternoon.",
            answerLabel: "Write the object pronoun:",
            expectedFormat: "One word.",
            placeholder: "one pronoun...",
            correctAnswer: "him",
            explanation: "The object form of \"he\" is \"him\": I visit him.",
            translation: "Mi hermano esta enfermo. Lo visito cada tarde.",
          },
        ],
      },
      {
        id: "pronouns-possessive",
        label: "Possessive Adjectives",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 3 · LESSON 3",
        title: "Pronouns — Possessive Adjectives",
        description:
          "Say who owns something with my, your, his, her, its, our, their. In English the possessive never changes with the object: it changes with the owner.",
        objectives: [
          "Choose the possessive adjective by the owner",
          "Place the possessive before the noun",
          "Avoid adding -s to the possessive",
        ],
        formulaLabel: "Possessive + noun",
        formula: "my book / her books",
        examples: [
          { source: "This is my book.", translation: "Este es mi libro." },
          { source: "Her books are new.", translation: "Sus libros son nuevos." },
          { source: "Our class starts at eight.", translation: "Nuestra clase empieza a las ocho." },
        ],
        xpReward: 66,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "pr-l3-e1",
            type: "choice",
            instruction: "Choose the possessive adjective for a female owner.",
            hint: "The owner is Ana, one woman. The number of books does not change the possessive.",
            prompt: "Ana has two books. _____ books are new.",
            options: ["Her", "Hers", "Their"],
            correctAnswer: "Her",
            explanation: "\"Her\" goes before the noun. \"Hers\" is used alone, without a noun after it.",
            translation: "Ana tiene dos libros. Sus libros son nuevos.",
          },
          {
            id: "pr-l3-e2",
            type: "input",
            instruction: "Write the possessive adjective that matches \"I\".",
            hint: "Write ONE word: the possessive form of \"I\", placed before the noun.",
            prompt: "This is _____ notebook.",
            answerLabel: "Write the possessive:",
            expectedFormat: "One word.",
            placeholder: "one word...",
            correctAnswer: "my",
            explanation: "The possessive adjective of \"I\" is \"my\": my notebook.",
            translation: "Este es mi cuaderno.",
          },
          {
            id: "pr-l3-e3",
            type: "choice",
            instruction: "Choose the correct possessive for the subject \"We\".",
            hint: "The owner is the group that includes the speaker.",
            prompt: "We are classmates. _____ classroom is on the second floor.",
            options: ["Our", "Us", "Ours"],
            correctAnswer: "Our",
            explanation: "\"Our\" is the possessive adjective before a noun. \"Us\" is an object pronoun and \"ours\" stands alone.",
            translation: "Somos companeros. Nuestra aula esta en el segundo piso.",
          },
          {
            id: "pr-l3-e4",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "The possessive goes immediately before the noun it owns.",
            prompt: "sister / is / This / my",
            options: ["This", "is", "my", "sister"],
            correctAnswer: "this is my sister",
            explanation: "Order: demonstrative + verb + possessive + noun: This is my sister.",
            translation: "Esta es mi hermana.",
          },
        ],
      },
    ],
  },

  "verb-to-be": {
    lessonTopics: [
      {
        id: "verb-to-be-affirmative",
        label: "Affirmative Sentences",
        state: "active",
        marker: "1",
        levelText: "LEVEL 4 · LESSON 1",
        title: "Verb To Be — Affirmative",
        description:
          "Describe identity, state and condition using am, is and are. Each subject takes only one of the three forms.",
        objectives: [
          "Use am / is / are correctly with each subject pronoun",
          "Form affirmative sentences about identity and state",
          "Recognize short descriptions using the verb to be",
        ],
        formulaLabel: "Subject + am/is/are + complement",
        formula: "I am / She is / They are",
        examples: [
          { source: "I am a student.", translation: "Yo soy estudiante." },
          { source: "She is happy.", translation: "Ella esta feliz." },
          { source: "They are at school.", translation: "Ellos estan en la escuela." },
        ],
        xpReward: 117,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "verb-to-be-aff-ex1",
            type: "choice",
            instruction: "Choose the form of the verb to be for \"She\".",
            hint: "Each subject takes one form only: I -> am, he/she/it -> is, you/we/they -> are.",
            prompt: "She _____ a teacher.",
            options: ["am", "is", "are"],
            correctAnswer: "is",
            explanation: "\"She\" is third person singular, so the form is \"is\".",
            translation: "Ella es profesora.",
          },
          {
            id: "verb-to-be-aff-ex2",
            type: "input",
            instruction: "Write the form of the verb to be for \"We\".",
            hint: "Write ONE word. Plural subjects take the same form as \"you\" and \"they\".",
            prompt: "We _____ ready.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "are",
            explanation: "\"We\" is plural, so the verb to be is \"are\".",
            translation: "Estamos listos.",
          },
          {
            id: "verb-to-be-aff-ex3",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "Order: subject + verb to be + complement. The article \"a\" is already inside the block.",
            prompt: "a student / I / am",
            options: ["I", "am", "a student"],
            correctAnswer: "i am a student",
            explanation: "The subject comes first and the verb to be follows: I am a student.",
            translation: "Soy estudiante.",
          },
          {
            id: "verb-to-be-aff-ex4",
            type: "choice",
            instruction: "Choose the form of the verb to be for \"They\".",
            hint: "\"They\" is plural, so it cannot take a singular form.",
            prompt: "They _____ at school today.",
            options: ["is", "am", "are"],
            correctAnswer: "are",
            explanation: "Plural subjects take \"are\": They are at school.",
            translation: "Ellos estan en la escuela hoy.",
          },
          {
            id: "verb-to-be-aff-ex5",
            type: "input",
            instruction: "Write the form of the verb to be for \"I\".",
            hint: "Write ONE word. The subject \"I\" has its own exclusive form.",
            prompt: "I _____ from Ecuador.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word. The contraction \"'m\" is also accepted.",
            placeholder: "one verb...",
            correctAnswer: "am",
            acceptedAnswers: ["am", "'m", "m"],
            explanation: "\"I\" always takes \"am\": I am from Ecuador.",
            translation: "Soy de Ecuador.",
          },
        ],
      },
      {
        id: "verb-to-be-negative",
        label: "Negative Sentences",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 4 · LESSON 2",
        title: "Verb To Be — Negative",
        description:
          "Deny or contradict identity and state using am not, isn't and aren't. The word \"not\" always goes after the verb.",
        objectives: [
          "Form negative sentences with am not / isn't / aren't",
          "Use short negative contractions naturally",
          "Contrast affirmative and negative statements",
        ],
        formulaLabel: "Subject + am not/isn't/aren't + complement",
        formula: "I am not / She isn't / They aren't",
        examples: [
          { source: "I am not tired.", translation: "No estoy cansado." },
          { source: "He isn't at home.", translation: "El no esta en casa." },
          { source: "We aren't late.", translation: "No estamos tarde." },
        ],
        xpReward: 117,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "verb-to-be-neg-ex1",
            type: "choice",
            instruction: "Choose the negative form of the verb to be for \"She\".",
            hint: "Keep the same form as the affirmative (is) and add not: is + not = isn't.",
            prompt: "She _____ my sister.",
            options: ["isn't", "aren't", "am not"],
            correctAnswer: "isn't",
            explanation: "Third person singular uses \"isn't\" (is not). \"Aren't\" is plural and \"am not\" is only for I.",
            translation: "Ella no es mi hermana.",
          },
          {
            id: "verb-to-be-neg-ex2",
            type: "input",
            instruction: "Write the negative form of the verb to be for \"They\".",
            hint: "Write ONE word: the contraction of are + not.",
            prompt: "They _____ ready yet.",
            answerLabel: "Write the negative verb:",
            expectedFormat: "One word. \"are not\" is also accepted.",
            placeholder: "one word...",
            correctAnswer: "aren't",
            acceptedAnswers: ["aren't", "arent", "are not"],
            explanation: "Plural subjects use aren't (are not): They aren't ready.",
            translation: "Ellos no estan listos todavia.",
          },
          {
            id: "verb-to-be-neg-ex3",
            type: "reorder",
            instruction: "Build the negative sentence using every word once.",
            hint: "In English \"not\" goes after the verb to be, never before it.",
            prompt: "not / tired / I / am",
            options: ["I", "am", "not", "tired"],
            correctAnswer: "i am not tired",
            explanation: "Order: subject + verb to be + not + complement: I am not tired.",
            translation: "No estoy cansado.",
          },
          {
            id: "verb-to-be-neg-ex4",
            type: "choice",
            instruction: "Choose the negative form of the verb to be for \"We\".",
            hint: "One of the options is not a real English word.",
            prompt: "We _____ from Canada.",
            options: ["isn't", "aren't", "amn't"],
            correctAnswer: "aren't",
            explanation: "\"We\" is plural, so it uses aren't. \"Amn't\" does not exist in standard English.",
            translation: "No somos de Canada.",
          },
        ],
      },
      {
        id: "verb-to-be-questions",
        label: "Questions",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 4 · LESSON 3",
        title: "Verb To Be — Questions",
        description:
          "Ask yes/no questions with am, is and are by moving the verb before the subject, and answer with short answers.",
        objectives: [
          "Invert subject and verb to form questions",
          "Ask short yes/no questions with to be",
          "Give short answers (Yes, I am. / No, she isn't.)",
        ],
        formulaLabel: "Am/Is/Are + subject + complement?",
        formula: "Are you ready? / Is she a doctor?",
        examples: [
          { source: "Are you a student?", translation: "Eres estudiante?" },
          { source: "Is he your friend?", translation: "El es tu amigo?" },
          { source: "Yes, I am. / No, I'm not.", translation: "Si, lo soy. / No, no lo soy." },
        ],
        xpReward: 116,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "verb-to-be-q-ex1",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "A yes/no question starts with the verb to be, then the subject, then the complement.",
            prompt: "you / are / a student",
            options: ["are", "you", "a student"],
            correctAnswer: "are you a student",
            explanation: "In questions the verb goes before the subject: Are you a student?",
            translation: "Eres estudiante?",
          },
          {
            id: "verb-to-be-q-ex2",
            type: "choice",
            instruction: "Choose the form of the verb to be that starts the question.",
            hint: "The subject is \"she\", so use the form that matches third person singular.",
            prompt: "_____ she your teacher?",
            options: ["Is", "Are", "Am"],
            correctAnswer: "Is",
            explanation: "With \"she\" the question starts with \"Is\": Is she your teacher?",
            translation: "Ella es tu profesora?",
          },
          {
            id: "verb-to-be-q-ex3",
            type: "input",
            instruction: "Write the missing word of the short answer.",
            hint: "Write ONE word. A short answer repeats the verb to be that matches the subject \"I\".",
            prompt: "Are you ready? Yes, I _____ .",
            answerLabel: "Write the missing verb:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "am",
            explanation: "Short answers repeat the verb: Yes, I am. The contraction \"I'm\" is not used in short answers.",
            translation: "Estas listo? Si, lo estoy.",
          },
          {
            id: "verb-to-be-q-ex4",
            type: "choice",
            instruction: "Choose the form of the verb to be that starts the question.",
            hint: "The subject \"they\" is plural.",
            prompt: "_____ they at home?",
            options: ["Is", "Am", "Are"],
            correctAnswer: "Are",
            explanation: "Plural subjects take \"are\", also in questions: Are they at home?",
            translation: "Ellos estan en casa?",
          },
        ],
      },
    ],
  },
};
