import type { SkillContent } from "./contentTypes";

/**
 * Grammar levels 5-7, authored with the same 3-lesson structure used in
 * levels 1-4: representative lesson names and 4 unambiguous exercises each.
 */
export const GRAMMAR_LEVELS_5_TO_7: SkillContent = {
  "basic-questions": {
    lessonTopics: [
      {
        id: "basic-questions-to-be",
        label: "Yes/No with To Be",
        state: "active",
        marker: "1",
        levelText: "LEVEL 5 · LESSON 1",
        title: "Basic Questions — Yes/No with To Be",
        description:
          "Turn a statement into a question by moving am, is or are to the front. No auxiliary is added.",
        objectives: [
          "Invert the verb to be and the subject",
          "Ask yes/no questions about state and identity",
          "Answer with Yes, ... is / No, ... isn't",
        ],
        formulaLabel: "Am/Is/Are + subject + ... ?",
        formula: "Are you ready?",
        examples: [
          { source: "Are you ready?", translation: "Estas listo?" },
          { source: "Is she at home?", translation: "Ella esta en casa?" },
          { source: "No, she isn't.", translation: "No, no esta." },
        ],
        xpReward: 134,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "bq-l1-e1",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "The verb to be goes first, then the subject, then the adjective.",
            prompt: "you / are / ready",
            options: ["are", "you", "ready"],
            correctAnswer: "are you ready",
            explanation: "Yes/no questions with to be start with the verb: Are you ready?",
            translation: "Estas listo?",
          },
          {
            id: "bq-l1-e2",
            type: "choice",
            instruction: "Choose the word that starts the question correctly.",
            hint: "The sentence has no other verb, so the question needs a form of \"to be\", not \"do\".",
            prompt: "_____ she your friend?",
            options: ["Is", "Are", "Do"],
            correctAnswer: "Is",
            explanation: "\"She\" takes \"is\". \"Do\" would need a different main verb, such as \"Do you know her?\"",
            translation: "Ella es tu amiga?",
          },
          {
            id: "bq-l1-e3",
            type: "input",
            instruction: "Write the word that starts the question for the subject \"they\".",
            hint: "Write ONE word: the form of the verb to be that matches a plural subject.",
            prompt: "_____ they in the classroom?",
            answerLabel: "Write the first word:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one verb...",
            correctAnswer: "are",
            explanation: "Plural subjects take \"are\", so the question starts with Are.",
            translation: "Estan ellos en el aula?",
          },
          {
            id: "bq-l1-e4",
            type: "choice",
            instruction: "Choose the correct short answer.",
            hint: "A short answer repeats the same verb form used in the question, and nothing else.",
            prompt: "Is he a doctor? _____",
            options: ["No, he isn't.", "No, he doesn't.", "No, he not."],
            correctAnswer: "No, he isn't.",
            explanation: "The question uses \"is\", so the short answer uses isn't. \"Doesn't\" belongs to questions with do.",
            translation: "No, no lo es.",
          },
        ],
      },
      {
        id: "basic-questions-do-does",
        label: "Yes/No with Do/Does",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 5 · LESSON 2",
        title: "Basic Questions — Yes/No with Do/Does",
        description:
          "When the sentence has an action verb, questions need the auxiliary Do or Does and the main verb stays in base form.",
        objectives: [
          "Choose between Do and Does",
          "Keep the main verb in base form",
          "Answer with Yes, I do / No, he doesn't",
        ],
        formulaLabel: "Do/Does + subject + base verb ... ?",
        formula: "Do you work? / Does he work?",
        examples: [
          { source: "Do you speak English?", translation: "Hablas ingles?" },
          { source: "Does she live here?", translation: "Ella vive aqui?" },
          { source: "Yes, I do.", translation: "Si." },
        ],
        xpReward: 133,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "bq-l2-e1",
            type: "choice",
            instruction: "Choose the correct auxiliary for the subject \"he\".",
            hint: "With he, she and it the auxiliary takes the -s, and the main verb loses it.",
            prompt: "_____ he work on Saturdays?",
            options: ["Do", "Does", "Is"],
            correctAnswer: "Does",
            explanation: "Third person singular uses Does + base verb: Does he work?",
            translation: "Trabaja el los sabados?",
          },
          {
            id: "bq-l2-e2",
            type: "input",
            instruction: "Write the auxiliary that starts the question for the subject \"you\".",
            hint: "Write ONE word: the auxiliary used with I, you, we and they.",
            prompt: "_____ you like pizza?",
            answerLabel: "Write the auxiliary:",
            expectedFormat: "One word.",
            placeholder: "one auxiliary...",
            correctAnswer: "do",
            explanation: "With \"you\" the auxiliary is Do: Do you like pizza?",
            translation: "Te gusta la pizza?",
          },
          {
            id: "bq-l2-e3",
            type: "choice",
            instruction: "Choose the correct question.",
            hint: "After Does the main verb never keeps the final -s.",
            prompt: "Which question is correct?",
            options: ["Does she works here?", "Does she work here?", "Do she work here?"],
            correctAnswer: "Does she work here?",
            explanation: "The auxiliary Does already carries the third person -s, so the main verb stays as \"work\".",
            translation: "Ella trabaja aqui?",
          },
          {
            id: "bq-l2-e4",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "Order: auxiliary + subject + base verb + complement.",
            prompt: "English / Do / speak / you",
            options: ["Do", "you", "speak", "English"],
            correctAnswer: "do you speak english",
            explanation: "The auxiliary opens the question: Do you speak English?",
            translation: "Hablas ingles?",
          },
        ],
      },
      {
        id: "basic-questions-wh",
        label: "Wh- Questions",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 5 · LESSON 3",
        title: "Basic Questions — Wh- Questions",
        description:
          "Ask for specific information with what, where, when and who. The question word goes before the verb or auxiliary.",
        objectives: [
          "Match each question word with the information it asks for",
          "Place the question word at the beginning",
          "Answer wh- questions with full information",
        ],
        formulaLabel: "Wh- word + auxiliary/verb + subject ... ?",
        formula: "Where do you live? / Who is she?",
        examples: [
          { source: "Where do you live?", translation: "Donde vives?" },
          { source: "When does the class start?", translation: "Cuando empieza la clase?" },
          { source: "Who is that man?", translation: "Quien es ese hombre?" },
        ],
        xpReward: 133,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "bq-l3-e1",
            type: "choice",
            instruction: "Choose the question word that asks about a place.",
            hint: "One word asks about place, one about time and one about a person.",
            prompt: "_____ do you live?",
            options: ["Where", "When", "Who"],
            correctAnswer: "Where",
            explanation: "\"Where\" asks about place. \"When\" asks about time and \"who\" about a person.",
            translation: "Donde vives?",
          },
          {
            id: "bq-l3-e2",
            type: "input",
            instruction: "Write the question word that asks about time.",
            hint: "Write ONE word: the wh- word used to ask at what moment something happens.",
            prompt: "_____ does the class start?",
            answerLabel: "Write the question word:",
            expectedFormat: "One word.",
            placeholder: "one question word...",
            correctAnswer: "when",
            explanation: "\"When\" asks about time: When does the class start? At eight.",
            translation: "Cuando empieza la clase?",
          },
          {
            id: "bq-l3-e3",
            type: "choice",
            instruction: "Choose the question that matches the answer given.",
            hint: "Read the answer first: it names a person, so the question must ask about a person.",
            prompt: "Answer: \"She is my sister.\" Question:",
            options: ["Who is she?", "Where is she?", "What is she?"],
            correctAnswer: "Who is she?",
            explanation: "The answer names a person, so the question word is \"who\".",
            translation: "Quien es ella?",
          },
          {
            id: "bq-l3-e4",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "Order: question word + auxiliary + subject + base verb.",
            prompt: "study / do / Where / you",
            options: ["Where", "do", "you", "study"],
            correctAnswer: "where do you study",
            explanation: "The wh- word comes first and the auxiliary follows: Where do you study?",
            translation: "Donde estudias?",
          },
        ],
      },
    ],
  },

  "present-continuous": {
    lessonTopics: [
      {
        id: "present-continuous-form",
        label: "Form: am/is/are + -ing",
        state: "active",
        marker: "1",
        levelText: "LEVEL 6 · LESSON 1",
        title: "Present Continuous — Form",
        description:
          "Describe an action happening right now. You always need two parts: the verb to be and the main verb with -ing.",
        objectives: [
          "Combine am/is/are with verb + ing",
          "Describe actions happening now",
          "Avoid dropping the verb to be",
        ],
        formulaLabel: "Subject + am/is/are + verb-ing",
        formula: "She is reading",
        examples: [
          { source: "They are studying now.", translation: "Ellos estan estudiando ahora." },
          { source: "I am cooking dinner.", translation: "Estoy cocinando la cena." },
          { source: "She is reading a book.", translation: "Ella esta leyendo un libro." },
        ],
        xpReward: 150,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "pc-l1-e1",
            type: "input",
            instruction: "Write the missing form of the verb to be for \"We\".",
            hint: "Write ONE word. Do not write the -ing verb: it is already in the sentence.",
            prompt: "We _____ reading a book.",
            answerLabel: "Write the verb to be:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "are",
            explanation: "The present continuous needs to be + -ing. With \"we\" the form is \"are\".",
            translation: "Estamos leyendo un libro.",
          },
          {
            id: "pc-l1-e2",
            type: "choice",
            instruction: "Choose the verb form that describes an action happening now.",
            hint: "The word \"now\" requires the continuous form, which has two parts.",
            prompt: "She _____ to music now.",
            options: ["listens", "is listening", "listen"],
            correctAnswer: "is listening",
            explanation: "\"Now\" marks an action in progress, so the present continuous \"is listening\" is used.",
            translation: "Ella esta escuchando musica ahora.",
          },
          {
            id: "pc-l1-e3",
            type: "choice",
            instruction: "Choose the complete present continuous sentence.",
            hint: "The verb to be cannot be omitted in English, even if Spanish allows it.",
            prompt: "Which sentence is correct?",
            options: ["He working right now.", "He is working right now.", "He is work right now."],
            correctAnswer: "He is working right now.",
            explanation: "The structure needs both parts: is + working. Dropping either part is incorrect.",
            translation: "El esta trabajando ahora mismo.",
          },
          {
            id: "pc-l1-e4",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "Order: subject + verb to be + verb with -ing + complement.",
            prompt: "dinner / I / cooking / am",
            options: ["I", "am", "cooking", "dinner"],
            correctAnswer: "i am cooking dinner",
            explanation: "The two parts stay together right after the subject: I am cooking dinner.",
            translation: "Estoy cocinando la cena.",
          },
        ],
      },
      {
        id: "present-continuous-spelling",
        label: "Spelling of -ing",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 6 · LESSON 2",
        title: "Present Continuous — Spelling of -ing",
        description:
          "Three spelling rules cover almost every verb: drop the final e, double the final consonant, or just add -ing.",
        objectives: [
          "Drop final e before -ing (write -> writing)",
          "Double the final consonant (run -> running)",
          "Add -ing with no change (study -> studying)",
        ],
        formulaLabel: "verb + ing (with spelling changes)",
        formula: "write -> writing / run -> running",
        examples: [
          { source: "She is writing an email.", translation: "Ella esta escribiendo un correo." },
          { source: "He is running in the park.", translation: "El esta corriendo en el parque." },
          { source: "They are studying for the exam.", translation: "Ellos estan estudiando para el examen." },
        ],
        xpReward: 150,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "pc-l2-e1",
            type: "input",
            instruction: "Write the -ing form of the verb \"write\".",
            hint: "Write ONE word. The verb ends in a silent e, so the e disappears before -ing.",
            prompt: "She is _____ an email. (write)",
            answerLabel: "Write the -ing form:",
            expectedFormat: "One word ending in -ing.",
            placeholder: "verb + ing...",
            correctAnswer: "writing",
            explanation: "Verbs ending in silent e drop it: write -> writing (not \"writeing\").",
            translation: "Ella esta escribiendo un correo.",
          },
          {
            id: "pc-l2-e2",
            type: "choice",
            instruction: "Choose the correct -ing form of \"run\".",
            hint: "The verb ends in one vowel + one consonant, so the consonant doubles.",
            prompt: "He is _____ in the park.",
            options: ["runing", "running", "runnning"],
            correctAnswer: "running",
            explanation: "Short verbs ending in vowel + consonant double the consonant: run -> running.",
            translation: "El esta corriendo en el parque.",
          },
          {
            id: "pc-l2-e3",
            type: "input",
            instruction: "Write the -ing form of the verb \"study\".",
            hint: "Write ONE word. Verbs ending in y keep the y before -ing; nothing is doubled or removed.",
            prompt: "They are _____ for the exam. (study)",
            answerLabel: "Write the -ing form:",
            expectedFormat: "One word ending in -ing.",
            placeholder: "verb + ing...",
            correctAnswer: "studying",
            explanation: "The y stays before -ing: study -> studying.",
            translation: "Ellos estan estudiando para el examen.",
          },
          {
            id: "pc-l2-e4",
            type: "choice",
            instruction: "Choose the correctly spelled -ing form.",
            hint: "\"Make\" ends in a silent e.",
            prompt: "I am _____ a cake.",
            options: ["makeing", "making", "makking"],
            correctAnswer: "making",
            explanation: "make -> making: the silent e is dropped before -ing.",
            translation: "Estoy haciendo un pastel.",
          },
        ],
      },
      {
        id: "present-continuous-negative-questions",
        label: "Negatives and Questions",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 6 · LESSON 3",
        title: "Present Continuous — Negatives and Questions",
        description:
          "Negatives add \"not\" after the verb to be, and questions move the verb to be to the front. The -ing verb never changes.",
        objectives: [
          "Form negatives with isn't / aren't + verb-ing",
          "Form questions with Is/Are + subject + verb-ing",
          "Keep the -ing form unchanged",
        ],
        formulaLabel: "Am/Is/Are (+ not) + subject + verb-ing",
        formula: "She isn't working / Are you working?",
        examples: [
          { source: "She isn't working today.", translation: "Ella no esta trabajando hoy." },
          { source: "Are you listening to me?", translation: "Me estas escuchando?" },
          { source: "They aren't sleeping.", translation: "Ellos no estan durmiendo." },
        ],
        xpReward: 150,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "pc-l3-e1",
            type: "choice",
            instruction: "Choose the correct negative form.",
            hint: "\"Not\" attaches to the verb to be, never to the -ing verb.",
            prompt: "She _____ working today.",
            options: ["isn't", "doesn't", "not is"],
            correctAnswer: "isn't",
            explanation: "The present continuous negative uses isn't + verb-ing. \"Doesn't\" belongs to the simple present.",
            translation: "Ella no esta trabajando hoy.",
          },
          {
            id: "pc-l3-e2",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "Order: verb to be + subject + verb with -ing.",
            prompt: "listening / you / Are",
            options: ["Are", "you", "listening"],
            correctAnswer: "are you listening",
            explanation: "The verb to be moves to the front and the -ing form stays: Are you listening?",
            translation: "Estas escuchando?",
          },
          {
            id: "pc-l3-e3",
            type: "input",
            instruction: "Write the missing negative form of the verb to be for \"They\".",
            hint: "Write ONE word: the contraction of are + not. Do not write the -ing verb.",
            prompt: "They _____ sleeping right now.",
            answerLabel: "Write the negative verb:",
            expectedFormat: "One word. \"are not\" is also accepted.",
            placeholder: "one word...",
            correctAnswer: "aren't",
            acceptedAnswers: ["aren't", "arent", "are not"],
            explanation: "Plural subjects use aren't + verb-ing: They aren't sleeping.",
            translation: "Ellos no estan durmiendo ahora.",
          },
          {
            id: "pc-l3-e4",
            type: "choice",
            instruction: "Choose the correct question.",
            hint: "In the present continuous the question never uses \"do\" or \"does\".",
            prompt: "Which question is correct?",
            options: ["Does he working now?", "Is he working now?", "He is working now?"],
            correctAnswer: "Is he working now?",
            explanation: "The verb to be starts the question: Is he working now?",
            translation: "El esta trabajando ahora?",
          },
        ],
      },
    ],
  },

  "simple-past": {
    lessonTopics: [
      {
        id: "simple-past-regular",
        label: "Regular Verbs (-ed)",
        state: "active",
        marker: "1",
        levelText: "LEVEL 7 · LESSON 1",
        title: "Simple Past — Regular Verbs",
        description:
          "Talk about finished actions. Regular verbs add -ed, and the form is the same for every subject.",
        objectives: [
          "Add -ed to regular verbs",
          "Use the same past form for every subject",
          "Recognize past time expressions",
        ],
        formulaLabel: "Subject + verb + ed",
        formula: "I worked / She walked",
        examples: [
          { source: "I visited my grandma.", translation: "Visite a mi abuela." },
          { source: "They played football yesterday.", translation: "Ellos jugaron futbol ayer." },
          { source: "She watched a movie last night.", translation: "Ella vio una pelicula anoche." },
        ],
        xpReward: 167,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "spa-l1-e1",
            type: "input",
            instruction: "Write the past form of the verb \"watch\".",
            hint: "Write ONE word. \"Watch\" is a regular verb, so it takes -ed.",
            prompt: "She _____ a movie last night. (watch)",
            answerLabel: "Write the past form:",
            expectedFormat: "One word ending in -ed.",
            placeholder: "verb + ed...",
            correctAnswer: "watched",
            explanation: "Regular verbs add -ed: watch -> watched. The form does not change with the subject.",
            translation: "Ella vio una pelicula anoche.",
          },
          {
            id: "spa-l1-e2",
            type: "choice",
            instruction: "Choose the correct past form of \"study\".",
            hint: "After a consonant, final y becomes ied.",
            prompt: "I _____ all weekend.",
            options: ["studyed", "studied", "studed"],
            correctAnswer: "studied",
            explanation: "Verbs ending in consonant + y change to ied: study -> studied.",
            translation: "Estudie todo el fin de semana.",
          },
          {
            id: "spa-l1-e3",
            type: "choice",
            instruction: "Choose the sentence that talks about a finished action.",
            hint: "Look for the past time expression; the verb must match it.",
            prompt: "Which sentence is correct?",
            options: ["Yesterday I work late.", "Yesterday I worked late.", "Yesterday I am working late."],
            correctAnswer: "Yesterday I worked late.",
            explanation: "\"Yesterday\" marks a finished action, so the verb must be in the simple past: worked.",
            translation: "Ayer trabaje tarde.",
          },
          {
            id: "spa-l1-e4",
            type: "reorder",
            instruction: "Build the sentence using every word once.",
            hint: "Order: subject + past verb + object + time expression.",
            prompt: "yesterday / played / They / football",
            options: ["They", "played", "football", "yesterday"],
            correctAnswer: "they played football yesterday",
            explanation: "The time expression goes at the end: They played football yesterday.",
            translation: "Ellos jugaron futbol ayer.",
          },
        ],
      },
      {
        id: "simple-past-irregular",
        label: "Irregular Verbs",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 7 · LESSON 2",
        title: "Simple Past — Irregular Verbs",
        description:
          "Some very common verbs do not take -ed and must be memorized: go -> went, have -> had, see -> saw.",
        objectives: [
          "Recognize the most common irregular past forms",
          "Avoid adding -ed to irregular verbs",
          "Use irregular verbs in short sentences",
        ],
        formulaLabel: "Subject + irregular past",
        formula: "go -> went / see -> saw",
        examples: [
          { source: "Yesterday I went to school.", translation: "Ayer fui a la escuela." },
          { source: "We had lunch at noon.", translation: "Almorzamos al mediodia." },
          { source: "I saw your brother.", translation: "Vi a tu hermano." },
        ],
        xpReward: 167,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "spa-l2-e1",
            type: "choice",
            instruction: "Choose the past form of the verb \"go\".",
            hint: "\"Go\" is irregular, so it does not take -ed and it is not the -ing form.",
            prompt: "Yesterday, I _____ to school.",
            options: ["go", "went", "going"],
            correctAnswer: "went",
            explanation: "The past of go is went. \"Goed\" does not exist.",
            translation: "Ayer fui a la escuela.",
          },
          {
            id: "spa-l2-e2",
            type: "input",
            instruction: "Write the past form of the verb \"have\".",
            hint: "Write ONE word. \"Have\" is irregular: it becomes a three-letter word.",
            prompt: "We _____ lunch at noon. (have)",
            answerLabel: "Write the past form:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "had",
            explanation: "The past of have is had, for every subject.",
            translation: "Almorzamos al mediodia.",
          },
          {
            id: "spa-l2-e3",
            type: "input",
            instruction: "Write the past form of the verb \"see\".",
            hint: "Write ONE word. \"See\" is irregular; the past has three letters and starts with s.",
            prompt: "I _____ your brother at the park. (see)",
            answerLabel: "Write the past form:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "saw",
            explanation: "The past of see is saw. \"Seed\" and \"seen\" are not simple past forms here.",
            translation: "Vi a tu hermano en el parque.",
          },
          {
            id: "spa-l2-e4",
            type: "choice",
            instruction: "Choose the sentence with the correct irregular past.",
            hint: "Irregular verbs never take -ed.",
            prompt: "Which sentence is correct?",
            options: ["She eated pizza.", "She ate pizza.", "She eat pizza yesterday."],
            correctAnswer: "She ate pizza.",
            explanation: "The past of eat is ate. \"Eated\" does not exist and \"eat\" is the present form.",
            translation: "Ella comio pizza.",
          },
        ],
      },
      {
        id: "simple-past-negative-questions",
        label: "Negatives and Questions",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 7 · LESSON 3",
        title: "Simple Past — Negatives and Questions",
        description:
          "Use did / didn't for negatives and questions. The auxiliary carries the past, so the main verb returns to its base form.",
        objectives: [
          "Form negatives with didn't + base verb",
          "Form questions with Did + subject + base verb",
          "Avoid double past marking",
        ],
        formulaLabel: "Subject + didn't + base verb",
        formula: "I didn't go / Did you go?",
        examples: [
          { source: "I didn't go to the party.", translation: "No fui a la fiesta." },
          { source: "Did you see the movie?", translation: "Viste la pelicula?" },
          { source: "She didn't study last night.", translation: "Ella no estudio anoche." },
        ],
        xpReward: 166,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "spa-l3-e1",
            type: "choice",
            instruction: "Choose the correct verb form after \"didn't\".",
            hint: "\"Didn't\" already marks the past, so the main verb goes back to its base form.",
            prompt: "I didn't _____ to the party.",
            options: ["went", "go", "going"],
            correctAnswer: "go",
            explanation: "After didn't the verb is always in base form: I didn't go.",
            translation: "No fui a la fiesta.",
          },
          {
            id: "spa-l3-e2",
            type: "input",
            instruction: "Write the missing negative auxiliary.",
            hint: "Write ONE word: the past negative contraction of \"do\".",
            prompt: "She _____ study last night.",
            answerLabel: "Write the auxiliary:",
            expectedFormat: "One word. \"did not\" is also accepted.",
            placeholder: "one auxiliary...",
            correctAnswer: "didn't",
            acceptedAnswers: ["didn't", "didnt", "did not"],
            explanation: "The simple past negative is didn't + base verb, for every subject.",
            translation: "Ella no estudio anoche.",
          },
          {
            id: "spa-l3-e3",
            type: "reorder",
            instruction: "Build the question using every word once.",
            hint: "Order: auxiliary Did + subject + base verb + object.",
            prompt: "the movie / Did / see / you",
            options: ["Did", "you", "see", "the movie"],
            correctAnswer: "did you see the movie",
            explanation: "Past questions start with Did and keep the base verb: Did you see the movie?",
            translation: "Viste la pelicula?",
          },
          {
            id: "spa-l3-e4",
            type: "choice",
            instruction: "Choose the correct past question.",
            hint: "The past is marked only once, in the auxiliary.",
            prompt: "Which question is correct?",
            options: ["Did she went home?", "Did she go home?", "Did she goes home?"],
            correctAnswer: "Did she go home?",
            explanation: "Did carries the past, so the main verb stays as \"go\".",
            translation: "Ella se fue a casa?",
          },
        ],
      },
    ],
  },
};
