import type { SkillContent } from "./contentTypes";

/**
 * Listening skill: every level has 3 sub-lessons with representative names.
 * Every exercise states exactly how the answer must be written (digits vs
 * words, full sentence vs single item), and a transcript is always available
 * from the exercise screen for people who cannot use the audio.
 */
export const LISTENING_CONTENT: SkillContent = {
  "listening-l1": {
    lessonTopics: [
      {
        id: "listening-l1-numbers",
        label: "Numbers 1-20",
        state: "active",
        marker: "1",
        levelText: "LEVEL 1 · LESSON 1",
        title: "Numbers & Dates — Numbers 1-20",
        description:
          "Recognize spoken numbers and write them down. Pay attention to pairs that sound similar, like thirteen and thirty.",
        objectives: [
          "Recognize numbers from one to twenty",
          "Write a heard number as digits",
          "Distinguish -teen from -ty endings",
        ],
        formulaLabel: "Audio -> number",
        formula: "thirteen = 13 / thirty = 30",
        examples: [
          { source: "I have thirteen books.", translation: "Tengo trece libros." },
          { source: "The room is number fifteen.", translation: "El cuarto es el numero quince." },
        ],
        xpReward: 34,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls1-l1-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence in English and write the number with digits (for example 12, not twelve). Use the transcript button if you cannot hear the audio.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "I have thirteen books.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence. The number must be written with digits.",
            placeholder: "I have 13 ...",
            correctAnswer: "i have 13 books",
            acceptedAnswers: ["i have 13 books", "i have thirteen books"],
            explanation: "The audio says thirteen (13), not thirty (30). The -teen ending is stressed at the end of the word.",
            translation: "Tengo trece libros.",
          },
          {
            id: "ls1-l1-e2",
            type: "listening",
            instruction: "Listen and write only the number you hear.",
            hint: "Do NOT write the whole sentence: write only the number, using digits.",
            prompt: "Write only the number that appears in the audio.",
            audioText: "The room is number fifteen.",
            answerLabel: "Write only the number (digits):",
            expectedFormat: "Digits only, for example: 7",
            placeholder: "a number...",
            correctAnswer: "15",
            acceptedAnswers: ["15", "fifteen"],
            explanation: "The audio says fifteen, so the number is 15.",
            translation: "El cuarto es el numero quince.",
          },
          {
            id: "ls1-l1-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence and use digits for the number. There are two numbers only in the translation, not in the audio.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "There are twenty students in the class.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, number written with digits.",
            placeholder: "There are 20 ...",
            correctAnswer: "there are 20 students in the class",
            acceptedAnswers: ["there are 20 students in the class", "there are twenty students in the class"],
            explanation: "\"There are\" is used for plural nouns, and twenty is written 20.",
            translation: "Hay veinte estudiantes en la clase.",
          },
        ],
      },
      {
        id: "listening-l1-prices",
        label: "Prices and Quantities",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 1 · LESSON 2",
        title: "Numbers & Dates — Prices and Quantities",
        description:
          "Catch prices and quantities in short sentences, including the currency word.",
        objectives: [
          "Recognize prices in dollars",
          "Write a price with digits",
          "Catch quantities in a shopping context",
        ],
        formulaLabel: "Audio -> price",
        formula: "five dollars = 5 dollars",
        examples: [
          { source: "It costs five dollars.", translation: "Cuesta cinco dolares." },
          { source: "I need two kilos of rice.", translation: "Necesito dos kilos de arroz." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls1-l2-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the number with digits and keep the currency word: for example \"3 dollars\".",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "It costs five dollars.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, number with digits.",
            placeholder: "It costs 5 ...",
            correctAnswer: "it costs 5 dollars",
            acceptedAnswers: ["it costs 5 dollars", "it costs five dollars"],
            explanation: "The subject \"it\" refers to the product, and the price is 5 dollars.",
            translation: "Cuesta cinco dolares.",
          },
          {
            id: "ls1-l2-e2",
            type: "listening",
            instruction: "Listen and write only the price you hear.",
            hint: "Write only the number and the currency word, nothing else: for example \"8 dollars\".",
            prompt: "Write only the price mentioned in the audio.",
            audioText: "The ticket is twelve dollars.",
            answerLabel: "Write only the price:",
            expectedFormat: "Number with digits + currency word.",
            placeholder: "12 dollars",
            correctAnswer: "12 dollars",
            acceptedAnswers: ["12 dollars", "twelve dollars"],
            explanation: "The audio says twelve dollars, so the price is 12 dollars.",
            translation: "El boleto cuesta doce dolares.",
          },
          {
            id: "ls1-l2-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence with the quantity in digits and the unit in words.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "I need two kilos of rice.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, quantity with digits.",
            placeholder: "I need 2 ...",
            correctAnswer: "i need 2 kilos of rice",
            acceptedAnswers: ["i need 2 kilos of rice", "i need two kilos of rice"],
            explanation: "Quantities use the pattern number + unit + of + product: two kilos of rice.",
            translation: "Necesito dos kilos de arroz.",
          },
        ],
      },
      {
        id: "listening-l1-dates",
        label: "Days and Dates",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 1 · LESSON 3",
        title: "Numbers & Dates — Days and Dates",
        description:
          "Understand days of the week and dates said with ordinal numbers (first, second, twenty-fifth).",
        objectives: [
          "Recognize the days of the week",
          "Understand ordinal dates",
          "Write a heard date",
        ],
        formulaLabel: "Month + ordinal day",
        formula: "July 25th",
        examples: [
          { source: "Today is July 25th.", translation: "Hoy es 25 de julio." },
          { source: "The meeting is on Monday.", translation: "La reunion es el lunes." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls1-l3-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the month in words and the day with digits plus its ending: 25th.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Today is July 25th.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence. Day as digits + th/st/nd.",
            placeholder: "Today is July 25th",
            correctAnswer: "today is july 25th",
            acceptedAnswers: ["today is july 25th", "today is july 25", "today is july twenty fifth"],
            explanation: "English says the month first and then the ordinal day: July 25th.",
            translation: "Hoy es 25 de julio.",
          },
          {
            id: "ls1-l3-e2",
            type: "listening",
            instruction: "Listen and write only the day of the week you hear.",
            hint: "Write ONE word: the name of the day, without the preposition \"on\".",
            prompt: "Write only the day of the week mentioned in the audio.",
            audioText: "The meeting is on Monday.",
            answerLabel: "Write only the day:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "a day...",
            correctAnswer: "monday",
            explanation: "The audio says \"on Monday\", so the day is Monday. Days of the week are always capitalized in English.",
            translation: "La reunion es el lunes.",
          },
          {
            id: "ls1-l3-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence. The day goes after the preposition \"on\".",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "My birthday is on Friday.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "My birthday is on ...",
            correctAnswer: "my birthday is on friday",
            explanation: "Days of the week take the preposition \"on\": on Friday.",
            translation: "Mi cumpleanos es el viernes.",
          },
        ],
      },
    ],
  },

  "listening-l2": {
    lessonTopics: [
      {
        id: "listening-l2-turns",
        label: "Turn Left, Turn Right",
        state: "active",
        marker: "1",
        levelText: "LEVEL 2 · LESSON 1",
        title: "Directions — Turn Left, Turn Right",
        description:
          "Follow short instructions built with imperative verbs: go, turn, take, cross.",
        objectives: [
          "Recognize movement verbs",
          "Understand left, right and straight",
          "Follow a two-step instruction",
        ],
        formulaLabel: "Verb + direction",
        formula: "Go straight / Turn left",
        examples: [
          { source: "Turn left at the corner.", translation: "Gira a la izquierda en la esquina." },
          { source: "Go straight and turn right.", translation: "Ve recto y gira a la derecha." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls2-l1-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "The audio has two instructions joined with \"and\". Write both, in the same order.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Go straight and turn right.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "Go straight and ...",
            correctAnswer: "go straight and turn right",
            explanation: "Directions are given with imperatives, with no subject: Go... and turn...",
            translation: "Ve recto y gira a la derecha.",
          },
          {
            id: "ls2-l1-e2",
            type: "listening",
            instruction: "Listen and write only the direction you hear (left or right).",
            hint: "Write ONE word: left or right. Do not write the whole sentence.",
            prompt: "Write only the direction mentioned in the audio.",
            audioText: "Turn left at the corner.",
            answerLabel: "Write only the direction:",
            expectedFormat: "One word: left or right.",
            placeholder: "left or right...",
            correctAnswer: "left",
            explanation: "The audio says \"Turn left at the corner\", so the direction is left.",
            translation: "Gira a la izquierda en la esquina.",
          },
          {
            id: "ls2-l1-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full instruction. \"Cross\" means to go from one side to the other.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Cross the street and go straight.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "Cross the street and ...",
            correctAnswer: "cross the street and go straight",
            explanation: "Both verbs are imperatives: Cross ... and go ...",
            translation: "Cruza la calle y ve recto.",
          },
        ],
      },
      {
        id: "listening-l2-places",
        label: "Places in the City",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 2 · LESSON 2",
        title: "Directions — Places in the City",
        description:
          "Identify the destination in a set of directions: bank, hospital, bus station, supermarket.",
        objectives: [
          "Recognize the names of common places",
          "Identify the destination in an instruction",
          "Understand next to, in front of and near",
        ],
        formulaLabel: "Place + preposition + place",
        formula: "The bank is next to the hospital.",
        examples: [
          { source: "The bank is next to the hospital.", translation: "El banco esta al lado del hospital." },
          { source: "The bus station is near the park.", translation: "La estacion de buses esta cerca del parque." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls2-l2-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence, including the article \"the\" before each place.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The bank is next to the hospital.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "The bank is next to ...",
            correctAnswer: "the bank is next to the hospital",
            explanation: "\"Next to\" means immediately beside, and each place keeps its article.",
            translation: "El banco esta al lado del hospital.",
          },
          {
            id: "ls2-l2-e2",
            type: "listening",
            instruction: "Listen and write only the destination you hear.",
            hint: "Write only the name of the place, without the article: for example \"park\".",
            prompt: "Write only the place mentioned as the destination.",
            audioText: "Go straight to the supermarket.",
            answerLabel: "Write only the place:",
            expectedFormat: "One or two words, no article.",
            placeholder: "a place...",
            correctAnswer: "supermarket",
            acceptedAnswers: ["supermarket", "the supermarket"],
            explanation: "The destination in the audio is the supermarket.",
            translation: "Ve recto hasta el supermercado.",
          },
          {
            id: "ls2-l2-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence. \"Near\" does not take \"to\" after it.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The bus station is near the park.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "The bus station is near ...",
            correctAnswer: "the bus station is near the park",
            explanation: "\"Near\" is followed directly by the place, with no preposition in between.",
            translation: "La estacion de buses esta cerca del parque.",
          },
        ],
      },
      {
        id: "listening-l2-distance",
        label: "Distances and Blocks",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 2 · LESSON 3",
        title: "Directions — Distances and Blocks",
        description:
          "Catch how far a place is: blocks, minutes on foot, first or second street.",
        objectives: [
          "Understand distance in blocks",
          "Understand time on foot",
          "Catch ordinal street numbers",
        ],
        formulaLabel: "Number + blocks / minutes",
        formula: "It's two blocks away.",
        examples: [
          { source: "It's two blocks away.", translation: "Esta a dos cuadras." },
          { source: "It's ten minutes on foot.", translation: "Esta a diez minutos caminando." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls2-l3-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the number with digits: for example \"2 blocks\".",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "It's two blocks away.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, number with digits.",
            placeholder: "It's 2 blocks away",
            correctAnswer: "it's 2 blocks away",
            acceptedAnswers: ["it's 2 blocks away", "it is 2 blocks away", "it's two blocks away"],
            explanation: "\"Away\" at the end expresses distance from the current position.",
            translation: "Esta a dos cuadras.",
          },
          {
            id: "ls2-l3-e2",
            type: "listening",
            instruction: "Listen and write only the number of minutes you hear.",
            hint: "Write only digits, without the word \"minutes\".",
            prompt: "Write only the number of minutes mentioned in the audio.",
            audioText: "It's ten minutes on foot.",
            answerLabel: "Write only the number:",
            expectedFormat: "Digits only, for example: 5",
            placeholder: "a number...",
            correctAnswer: "10",
            acceptedAnswers: ["10", "ten"],
            explanation: "The audio says ten minutes, so the number is 10.",
            translation: "Esta a diez minutos caminando.",
          },
          {
            id: "ls2-l3-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the ordinal number in words (first, second, third) exactly as you hear it.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Take the second street on the right.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, ordinal in words.",
            placeholder: "Take the second street ...",
            correctAnswer: "take the second street on the right",
            explanation: "Streets are counted with ordinals: the second street.",
            translation: "Toma la segunda calle a la derecha.",
          },
        ],
      },
    ],
  },

  "listening-l3": {
    lessonTopics: [
      {
        id: "listening-l3-short-answers",
        label: "Short Questions and Answers",
        state: "active",
        marker: "1",
        levelText: "LEVEL 3 · LESSON 1",
        title: "Dialogues — Short Questions and Answers",
        description:
          "Follow a two-line exchange and write both parts, including the short answer.",
        objectives: [
          "Identify question and answer in one audio",
          "Write short answers correctly",
          "Recognize rising question intonation",
        ],
        formulaLabel: "Question? + Short answer.",
        formula: "Are you ready? Yes, I am.",
        examples: [
          { source: "Are you ready? Yes, I am.", translation: "Estas listo? Si, lo estoy." },
          { source: "Are you coming? Yes, in a minute.", translation: "Vienes? Si, en un minuto." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls3-l1-e1",
            type: "listening",
            instruction: "Listen and write the whole dialogue you hear.",
            hint: "Write both lines in order: first the question, then the answer. Punctuation is not graded.",
            prompt: "Listen carefully and transcribe the two lines.",
            audioText: "Are you ready? Yes, I am.",
            answerLabel: "Write the dialogue you heard:",
            expectedFormat: "Both lines, in the same order.",
            placeholder: "Are you ready? Yes, I am.",
            correctAnswer: "are you ready yes i am",
            explanation: "The short answer repeats the verb of the question: Are you ready? Yes, I am.",
            translation: "Estas listo? Si, lo estoy.",
          },
          {
            id: "ls3-l1-e2",
            type: "listening",
            instruction: "Listen and write only the answer you hear.",
            hint: "Do NOT write the question: write only the second line of the dialogue.",
            prompt: "Write only the answer part of the dialogue.",
            audioText: "Is she your sister? No, she isn't.",
            answerLabel: "Write only the answer:",
            expectedFormat: "Only the answer line.",
            placeholder: "No, she ...",
            correctAnswer: "no she isn't",
            acceptedAnswers: ["no she isn't", "no she isnt", "no she is not"],
            explanation: "The negative short answer keeps the same verb: No, she isn't.",
            translation: "No, no lo es.",
          },
          {
            id: "ls3-l1-e3",
            type: "listening",
            instruction: "Listen and write the whole dialogue you hear.",
            hint: "Write both lines. The answer is not a simple yes: it adds a time expression.",
            prompt: "Listen carefully and transcribe the two lines.",
            audioText: "Are you coming? Yes, in a minute.",
            answerLabel: "Write the dialogue you heard:",
            expectedFormat: "Both lines, in the same order.",
            placeholder: "Are you coming? Yes, ...",
            correctAnswer: "are you coming yes in a minute",
            explanation: "\"In a minute\" means very soon and completes the affirmative answer.",
            translation: "Vienes? Si, en un minuto.",
          },
        ],
      },
      {
        id: "listening-l3-feelings",
        label: "Feelings and Reactions",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 3 · LESSON 2",
        title: "Dialogues — Feelings and Reactions",
        description:
          "Catch how characters feel: tired, worried, excited, glad. These adjectives follow the verb to be.",
        objectives: [
          "Recognize feeling adjectives",
          "Identify who feels what",
          "Understand short reactions",
        ],
        formulaLabel: "Subject + be + feeling",
        formula: "I'm so tired.",
        examples: [
          { source: "I'm so tired today.", translation: "Estoy muy cansado hoy." },
          { source: "That's great news!", translation: "Esas son buenas noticias." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls3-l2-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence. \"So\" before the adjective makes it stronger.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "I'm so tired today.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "I'm so ...",
            correctAnswer: "i'm so tired today",
            acceptedAnswers: ["i'm so tired today", "i am so tired today"],
            explanation: "Feelings use the verb to be plus an adjective: I'm tired.",
            translation: "Estoy muy cansado hoy.",
          },
          {
            id: "ls3-l2-e2",
            type: "listening",
            instruction: "Listen and write only the feeling adjective you hear.",
            hint: "Write ONE word: the adjective that describes the feeling.",
            prompt: "Write only the adjective that describes the feeling.",
            audioText: "She is very worried about the exam.",
            answerLabel: "Write only the adjective:",
            expectedFormat: "One word.",
            placeholder: "an adjective...",
            correctAnswer: "worried",
            explanation: "The adjective is \"worried\"; \"very\" is only an intensifier.",
            translation: "Ella esta muy preocupada por el examen.",
          },
          {
            id: "ls3-l2-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full reaction. It starts with \"That's\", the contraction of that is.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "That's great news!",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "That's ...",
            correctAnswer: "that's great news",
            acceptedAnswers: ["that's great news", "that is great news"],
            explanation: "\"That's great news!\" is a common positive reaction. \"News\" is always singular in English.",
            translation: "Esas son buenas noticias.",
          },
        ],
      },
      {
        id: "listening-l3-plans",
        label: "Making Plans",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 3 · LESSON 3",
        title: "Dialogues — Making Plans",
        description:
          "Understand invitations and arrangements: where, when and at what time people will meet.",
        objectives: [
          "Catch the time of an arrangement",
          "Understand invitations with Let's",
          "Identify the meeting place",
        ],
        formulaLabel: "Let's + base verb",
        formula: "Let's meet at seven.",
        examples: [
          { source: "Let's meet at seven.", translation: "Reunamonos a las siete." },
          { source: "See you at the cinema.", translation: "Nos vemos en el cine." },
        ],
        xpReward: 66,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls3-l3-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence and write the hour with digits: for example \"at 7\".",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Let's meet at seven.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, hour with digits.",
            placeholder: "Let's meet at 7",
            correctAnswer: "let's meet at 7",
            acceptedAnswers: ["let's meet at 7", "lets meet at 7", "let's meet at seven"],
            explanation: "\"Let's + base verb\" proposes a shared action, and the hour takes the preposition \"at\".",
            translation: "Reunamonos a las siete.",
          },
          {
            id: "ls3-l3-e2",
            type: "listening",
            instruction: "Listen and write only the place you hear.",
            hint: "Write only the meeting place, without the article: for example \"park\".",
            prompt: "Write only the place where they will meet.",
            audioText: "See you at the cinema.",
            answerLabel: "Write only the place:",
            expectedFormat: "One word, no article.",
            placeholder: "a place...",
            correctAnswer: "cinema",
            acceptedAnswers: ["cinema", "the cinema", "movie theater"],
            explanation: "The audio says \"at the cinema\", so the place is the cinema.",
            translation: "Nos vemos en el cine.",
          },
          {
            id: "ls3-l3-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full question. It is an invitation using \"Do you want to\".",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "Do you want to go to the park?",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full question.",
            placeholder: "Do you want to ...",
            correctAnswer: "do you want to go to the park",
            explanation: "Invitations often use \"Do you want to + base verb\".",
            translation: "Quieres ir al parque?",
          },
        ],
      },
    ],
  },

  "listening-l4": {
    lessonTopics: [
      {
        id: "listening-l4-times",
        label: "Times and Schedules",
        state: "active",
        marker: "1",
        levelText: "LEVEL 4 · LESSON 1",
        title: "News — Times and Schedules",
        description:
          "Catch exact times in announcements: arrivals, departures and opening hours.",
        objectives: [
          "Understand times with at",
          "Write a heard time with digits",
          "Catch schedule changes",
        ],
        formulaLabel: "Subject + verb + at + time",
        formula: "The train arrives at 8.",
        examples: [
          { source: "The train arrives at 8.", translation: "El tren llega a las 8." },
          { source: "The museum opens at nine thirty.", translation: "El museo abre a las nueve y media." },
        ],
        xpReward: 84,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls4-l1-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence and use digits for the hour.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The train arrives at 8.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, hour with digits.",
            placeholder: "The train arrives at 8",
            correctAnswer: "the train arrives at 8",
            acceptedAnswers: ["the train arrives at 8", "the train arrives at eight"],
            explanation: "Times take the preposition \"at\": at 8.",
            translation: "El tren llega a las 8.",
          },
          {
            id: "ls4-l1-e2",
            type: "listening",
            instruction: "Listen and write only the time you hear.",
            hint: "Write the time using digits and a colon: for example 9:30.",
            prompt: "Write only the time mentioned in the audio.",
            audioText: "The museum opens at nine thirty.",
            answerLabel: "Write only the time:",
            expectedFormat: "Digits with a colon, for example 7:15.",
            placeholder: "9:30",
            correctAnswer: "9:30",
            acceptedAnswers: ["9:30", "930", "nine thirty"],
            explanation: "\"Nine thirty\" is written 9:30.",
            translation: "El museo abre a las nueve y media.",
          },
          {
            id: "ls4-l1-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence and use digits for the hour.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The flight leaves at 6 in the morning.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, hour with digits.",
            placeholder: "The flight leaves at 6 ...",
            correctAnswer: "the flight leaves at 6 in the morning",
            acceptedAnswers: ["the flight leaves at 6 in the morning", "the flight leaves at six in the morning"],
            explanation: "\"In the morning\" specifies the part of the day after the exact time.",
            translation: "El vuelo sale a las 6 de la manana.",
          },
        ],
      },
      {
        id: "listening-l4-weather",
        label: "Weather Reports",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 4 · LESSON 2",
        title: "News — Weather Reports",
        description:
          "Catch the forecast: conditions and temperatures in a short weather report.",
        objectives: [
          "Recognize weather conditions",
          "Catch temperatures in degrees",
          "Understand tomorrow's forecast",
        ],
        formulaLabel: "It will be + condition",
        formula: "It will be rainy tomorrow.",
        examples: [
          { source: "It will be rainy tomorrow.", translation: "Estara lluvioso manana." },
          { source: "The temperature is 15 degrees.", translation: "La temperatura es de 15 grados." },
        ],
        xpReward: 83,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "ls4-l2-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full forecast sentence. \"Will be\" announces the future.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "It will be rainy tomorrow.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "It will be ...",
            correctAnswer: "it will be rainy tomorrow",
            explanation: "Forecasts use will + be + condition: It will be rainy.",
            translation: "Estara lluvioso manana.",
          },
          {
            id: "ls4-l2-e2",
            type: "listening",
            instruction: "Listen and write only the temperature you hear.",
            hint: "Write only digits and the word degrees: for example \"20 degrees\".",
            prompt: "Write only the temperature mentioned in the audio.",
            audioText: "The temperature is 15 degrees.",
            answerLabel: "Write only the temperature:",
            expectedFormat: "Digits + the word degrees.",
            placeholder: "15 degrees",
            correctAnswer: "15 degrees",
            acceptedAnswers: ["15 degrees", "fifteen degrees", "15"],
            explanation: "The audio says fifteen degrees, so the temperature is 15 degrees.",
            translation: "La temperatura es de 15 grados.",
          },
          {
            id: "ls4-l2-e3",
            type: "listening",
            instruction: "Listen and write only the weather condition you hear.",
            hint: "Write ONE word: the adjective that describes the weather.",
            prompt: "Write only the weather condition mentioned in the audio.",
            audioText: "It is cloudy in the north of the country.",
            answerLabel: "Write only the condition:",
            expectedFormat: "One word.",
            placeholder: "an adjective...",
            correctAnswer: "cloudy",
            explanation: "The condition is \"cloudy\"; the rest of the sentence gives the location.",
            translation: "Esta nublado en el norte del pais.",
          },
        ],
      },
      {
        id: "listening-l4-headlines",
        label: "Headlines: Who and What",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 4 · LESSON 3",
        title: "News — Headlines: Who and What",
        description:
          "Identify the two key pieces of a headline: who is involved and what happened.",
        objectives: [
          "Identify the subject of a headline",
          "Identify the main action",
          "Summarize a short news item",
        ],
        formulaLabel: "Who + what",
        formula: "The president visits the city.",
        examples: [
          { source: "The president visits the city today.", translation: "El presidente visita la ciudad hoy." },
          { source: "The new bridge opens next month.", translation: "El nuevo puente abre el proximo mes." },
        ],
        xpReward: 83,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "ls4-l3-e1",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full headline, keeping the article \"the\" at the beginning.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The president visits the city today.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence.",
            placeholder: "The president visits ...",
            correctAnswer: "the president visits the city today",
            explanation: "The headline follows subject + verb + object + time.",
            translation: "El presidente visita la ciudad hoy.",
          },
          {
            id: "ls4-l3-e2",
            type: "listening",
            instruction: "Listen and write only the main verb you hear.",
            hint: "Write ONE word: the verb of the headline, exactly as you hear it (with its -s if it has one).",
            prompt: "Write only the main verb of the headline.",
            audioText: "The new bridge opens next month.",
            answerLabel: "Write only the verb:",
            expectedFormat: "One word.",
            placeholder: "a verb...",
            correctAnswer: "opens",
            explanation: "The verb is \"opens\", with the third person -s because the subject is \"the new bridge\".",
            translation: "El nuevo puente abre el proximo mes.",
          },
          {
            id: "ls4-l3-e3",
            type: "listening",
            instruction: "Listen and write the sentence you hear.",
            hint: "Write the full sentence, including the number with digits.",
            prompt: "Listen carefully and transcribe the sentence.",
            audioText: "The city opens 3 new schools this year.",
            answerLabel: "Write the sentence you heard:",
            expectedFormat: "Full sentence, number with digits.",
            placeholder: "The city opens 3 ...",
            correctAnswer: "the city opens 3 new schools this year",
            acceptedAnswers: ["the city opens 3 new schools this year", "the city opens three new schools this year"],
            explanation: "The subject is \"the city\", so the verb takes -s: opens.",
            translation: "La ciudad abre 3 escuelas nuevas este ano.",
          },
        ],
      },
    ],
  },
};
