import type { SkillContent } from "./contentTypes";

/**
 * Speaking skill: every level has 3 sub-lessons with representative names and
 * its own bank of exercises. Speaking exercises can be answered with the
 * microphone or with the keyboard fallback, so each one states exactly which
 * sentence must be produced.
 */
export const SPEAKING_CONTENT: SkillContent = {
  "speaking-l1": {
    lessonTopics: [
      {
        id: "speaking-l1-greet",
        label: "Greet and Say Your Name",
        state: "active",
        marker: "1",
        levelText: "LEVEL 1 · LESSON 1",
        title: "Introductions — Greet and Say Your Name",
        description:
          "Say a greeting and your name in a single natural sentence, the way you would in a first meeting.",
        objectives: [
          "Pronounce a greeting clearly",
          "Say your name after the greeting",
          "Keep a natural falling intonation",
        ],
        formulaLabel: "Hello + I'm + name",
        formula: "Hello, I'm Maria.",
        examples: [
          { source: "Hello, I'm Maria.", translation: "Hola, soy Maria." },
          { source: "Hi, I'm Luis.", translation: "Hola, soy Luis." },
        ],
        xpReward: 34,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk1-l1-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Read the sentence in the box word by word. If you prefer the keyboard, use \"I'd rather type my answer\" and copy the same sentence.",
            prompt: "Hello, I'm Maria.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt. Punctuation is not graded.",
            placeholder: "Hello, I'm Maria.",
            correctAnswer: "hello i'm maria",
            acceptedAnswers: ["hello i'm maria", "hello i am maria"],
            explanation: "The greeting comes first and the introduction follows: Hello, I'm Maria.",
            translation: "Hola, soy Maria.",
          },
          {
            id: "sk1-l1-e2",
            type: "choice",
            instruction: "Choose the sentence you would say when you meet someone for the first time.",
            hint: "You need a greeting plus your name. Only one option has both.",
            prompt: "First meeting at a language school:",
            options: ["Hi, I'm Luis.", "Hi, my name Luis.", "Hi, I Luis."],
            correctAnswer: "Hi, I'm Luis.",
            explanation: "\"I'm\" is the contraction of I am. The other options are missing the verb.",
            translation: "Hola, soy Luis.",
          },
          {
            id: "sk1-l1-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Use the pattern \"Good morning\" + \"my name is\" + name. Say it as one sentence.",
            prompt: "Good morning, my name is Ana.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "Good morning, my name is Ana.",
            correctAnswer: "good morning my name is ana",
            explanation: "\"My name is + name\" is a complete introduction, more formal than \"I'm\".",
            translation: "Buenos dias, mi nombre es Ana.",
          },
        ],
      },
      {
        id: "speaking-l1-origin",
        label: "Say Where You Are From",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 1 · LESSON 2",
        title: "Introductions — Say Where You Are From",
        description:
          "Add your origin to the introduction with the pattern \"I'm from + place\".",
        objectives: [
          "Use I'm from + city or country",
          "Join name and origin in one sentence",
          "Answer the question Where are you from?",
        ],
        formulaLabel: "I'm from + place",
        formula: "I'm from Quito.",
        examples: [
          { source: "I'm from Quito, Ecuador.", translation: "Soy de Quito, Ecuador." },
          { source: "I'm Ana and I'm from Peru.", translation: "Soy Ana y soy de Peru." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk1-l2-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "The preposition \"from\" is always needed before the place.",
            prompt: "I'm from Quito, Ecuador.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I'm from Quito, Ecuador.",
            correctAnswer: "i'm from quito ecuador",
            acceptedAnswers: ["i'm from quito ecuador", "i am from quito ecuador"],
            explanation: "Origin is expressed with \"be from\": I'm from Quito.",
            translation: "Soy de Quito, Ecuador.",
          },
          {
            id: "sk1-l2-e2",
            type: "choice",
            instruction: "Choose the correct answer to \"Where are you from?\"",
            hint: "The answer must include the verb and the preposition \"from\".",
            prompt: "A: Where are you from? B: _____",
            options: ["I'm from Ecuador.", "I from Ecuador.", "I'm Ecuador from."],
            correctAnswer: "I'm from Ecuador.",
            explanation: "The pattern is subject + be + from + place.",
            translation: "Soy de Ecuador.",
          },
          {
            id: "sk1-l2-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Two ideas joined with \"and\": your name first, your origin second.",
            prompt: "I'm Ana and I'm from Peru.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I'm Ana and I'm from Peru.",
            correctAnswer: "i'm ana and i'm from peru",
            acceptedAnswers: ["i'm ana and i'm from peru", "i am ana and i am from peru"],
            explanation: "Each idea keeps its own verb: I'm Ana and I'm from Peru.",
            translation: "Soy Ana y soy de Peru.",
          },
        ],
      },
      {
        id: "speaking-l1-nice",
        label: "Nice to Meet You",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 1 · LESSON 3",
        title: "Introductions — Nice to Meet You",
        description:
          "Close a first conversation politely and return the courtesy.",
        objectives: [
          "Say Nice to meet you",
          "Return the courtesy with too",
          "Combine introduction and closing",
        ],
        formulaLabel: "Nice to meet you (too)",
        formula: "Nice to meet you too.",
        examples: [
          { source: "Nice to meet you.", translation: "Mucho gusto." },
          { source: "Nice to meet you too.", translation: "Mucho gusto tambien." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk1-l3-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Four words, fixed order. Do not add \"you\" at the beginning.",
            prompt: "Nice to meet you.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "Nice to meet you.",
            correctAnswer: "nice to meet you",
            explanation: "\"Nice to meet you\" is a fixed expression; the order never changes.",
            translation: "Mucho gusto.",
          },
          {
            id: "sk1-l3-e2",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Add \"too\" at the end to return the courtesy.",
            prompt: "Nice to meet you too.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "Nice to meet you too.",
            correctAnswer: "nice to meet you too",
            explanation: "\"Too\" at the end means \"tambien\" and returns the same idea.",
            translation: "Mucho gusto tambien.",
          },
          {
            id: "sk1-l3-e3",
            type: "choice",
            instruction: "Choose the polite way to close the introduction.",
            hint: "Only one option is a courtesy formula; the others answer different questions.",
            prompt: "A: I'm Sara. B: I'm Pablo. _____",
            options: ["Nice to meet you!", "Yes, please.", "See you yesterday."],
            correctAnswer: "Nice to meet you!",
            explanation: "After exchanging names, the standard closing is \"Nice to meet you\".",
            translation: "Mucho gusto.",
          },
        ],
      },
    ],
  },

  "speaking-l2": {
    lessonTopics: [
      {
        id: "speaking-l2-likes",
        label: "Say What You Like",
        state: "active",
        marker: "1",
        levelText: "LEVEL 2 · LESSON 1",
        title: "Hobbies — Say What You Like",
        description:
          "Talk about activities you enjoy. After \"like\" and \"love\" English uses the -ing form of the activity.",
        objectives: [
          "Use I like / I love + verb-ing",
          "Name common hobbies",
          "Pronounce -ing endings clearly",
        ],
        formulaLabel: "I like + verb-ing",
        formula: "I like reading.",
        examples: [
          { source: "I like playing football.", translation: "Me gusta jugar futbol." },
          { source: "I love listening to music.", translation: "Me encanta escuchar musica." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk2-l1-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Notice \"listening to music\": the preposition \"to\" is required after listen.",
            prompt: "I like listening to music.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I like listening to music.",
            correctAnswer: "i like listening to music",
            explanation: "After \"like\" the activity takes -ing, and \"listen\" always needs \"to\" before its object.",
            translation: "Me gusta escuchar musica.",
          },
          {
            id: "sk2-l1-e2",
            type: "choice",
            instruction: "Choose the correct form after \"like\".",
            hint: "After like / love / enjoy the activity is expressed with -ing.",
            prompt: "I like _____ football on weekends.",
            options: ["play", "playing", "played"],
            correctAnswer: "playing",
            explanation: "\"Like\" is followed by the -ing form: I like playing football.",
            translation: "Me gusta jugar futbol los fines de semana.",
          },
          {
            id: "sk2-l1-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "\"Love\" is stronger than \"like\" and follows the same -ing pattern.",
            prompt: "I love cooking with my family.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I love cooking with my family.",
            correctAnswer: "i love cooking with my family",
            explanation: "Same structure as \"like\": love + verb-ing.",
            translation: "Me encanta cocinar con mi familia.",
          },
        ],
      },
      {
        id: "speaking-l2-frequency",
        label: "Say How Often",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 2 · LESSON 2",
        title: "Hobbies — Say How Often",
        description:
          "Add frequency to your hobbies with always, usually, sometimes and never, or with expressions like twice a week.",
        objectives: [
          "Place frequency adverbs before the main verb",
          "Use expressions like twice a week",
          "Describe your own routine",
        ],
        formulaLabel: "Subject + adverb + verb",
        formula: "I usually play tennis.",
        examples: [
          { source: "I usually play tennis on Sundays.", translation: "Normalmente juego tenis los domingos." },
          { source: "I go to the gym twice a week.", translation: "Voy al gimnasio dos veces por semana." },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk2-l2-e1",
            type: "choice",
            instruction: "Choose the sentence with the frequency adverb in the correct position.",
            hint: "Frequency adverbs go between the subject and the main verb.",
            prompt: "Which sentence is correct?",
            options: ["I usually play tennis.", "I play usually tennis.", "Usually I play tennis on."],
            correctAnswer: "I usually play tennis.",
            explanation: "The adverb goes before the main verb: subject + usually + verb.",
            translation: "Normalmente juego tenis.",
          },
          {
            id: "sk2-l2-e2",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "\"Twice a week\" goes at the end of the sentence.",
            prompt: "I go to the gym twice a week.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I go to the gym twice a week.",
            correctAnswer: "i go to the gym twice a week",
            explanation: "Frequency expressions with a number go at the end: twice a week.",
            translation: "Voy al gimnasio dos veces por semana.",
          },
          {
            id: "sk2-l2-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "\"Never\" also goes before the main verb, and the verb stays affirmative.",
            prompt: "I never watch TV in the morning.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I never watch TV in the morning.",
            correctAnswer: "i never watch tv in the morning",
            explanation: "\"Never\" already makes the sentence negative, so no \"don't\" is added.",
            translation: "Nunca veo television en la manana.",
          },
        ],
      },
      {
        id: "speaking-l2-asking",
        label: "Ask About Hobbies",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 2 · LESSON 3",
        title: "Hobbies — Ask About Hobbies",
        description:
          "Keep the conversation going by asking other people what they like to do.",
        objectives: [
          "Ask What do you like doing?",
          "Ask about free time",
          "Answer and return the question",
        ],
        formulaLabel: "What do you like + verb-ing?",
        formula: "What do you like doing?",
        examples: [
          { source: "What do you like doing on weekends?", translation: "Que te gusta hacer los fines de semana?" },
          { source: "What about you?", translation: "Y tu?" },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk2-l3-e1",
            type: "speaking",
            instruction: "Say this exact question aloud.",
            hint: "The question keeps the auxiliary \"do\" and ends with the -ing form.",
            prompt: "What do you like doing on weekends?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "What do you like doing on weekends?",
            correctAnswer: "what do you like doing on weekends",
            explanation: "Structure: What + do + you + like + verb-ing.",
            translation: "Que te gusta hacer los fines de semana?",
          },
          {
            id: "sk2-l3-e2",
            type: "choice",
            instruction: "Choose the correct question.",
            hint: "The auxiliary \"do\" is required, and \"like\" keeps its base form after it.",
            prompt: "Which question is correct?",
            options: ["What you like doing?", "What do you like doing?", "What do you likes doing?"],
            correctAnswer: "What do you like doing?",
            explanation: "Questions in the simple present need the auxiliary do and a base verb.",
            translation: "Que te gusta hacer?",
          },
          {
            id: "sk2-l3-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud to return the question.",
            hint: "Three words, used after giving your own answer.",
            prompt: "What about you?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "What about you?",
            correctAnswer: "what about you",
            explanation: "\"What about you?\" returns the same question without repeating it.",
            translation: "Y tu?",
          },
        ],
      },
    ],
  },

  "speaking-l3": {
    lessonTopics: [
      {
        id: "speaking-l3-how-are-you",
        label: "How Are You?",
        state: "active",
        marker: "1",
        levelText: "LEVEL 3 · LESSON 1",
        title: "Small Talk — How Are You?",
        description:
          "Open a short conversation and answer the standard greeting question naturally.",
        objectives: [
          "Ask How are you?",
          "Answer with a short state phrase",
          "Return the question politely",
        ],
        formulaLabel: "How are you? / I'm fine, thanks.",
        formula: "How are you? - I'm fine, thanks.",
        examples: [
          { source: "How are you?", translation: "Como estas?" },
          { source: "I'm fine, thanks. And you?", translation: "Estoy bien, gracias. Y tu?" },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk3-l1-e1",
            type: "speaking",
            instruction: "Say this exact answer aloud.",
            hint: "Answer with your state and add \"thanks\". Do not add extra words.",
            prompt: "I'm fine, thanks.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I'm fine, thanks.",
            correctAnswer: "i'm fine thanks",
            acceptedAnswers: ["i'm fine thanks", "i am fine thanks"],
            explanation: "The standard answer is \"I'm fine, thanks\", with the verb to be.",
            translation: "Estoy bien, gracias.",
          },
          {
            id: "sk3-l1-e2",
            type: "choice",
            instruction: "Choose the natural answer to \"How are you?\"",
            hint: "The question asks about your state, not about your name or your age.",
            prompt: "A: How are you? B: _____",
            options: ["I'm fine, thanks.", "I'm twenty.", "I'm from Quito."],
            correctAnswer: "I'm fine, thanks.",
            explanation: "\"How are you?\" asks about state, so the answer describes how you feel.",
            translation: "Estoy bien, gracias.",
          },
          {
            id: "sk3-l1-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud to return the question.",
            hint: "Two words used right after your own answer.",
            prompt: "And you?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "And you?",
            correctAnswer: "and you",
            explanation: "\"And you?\" gives the turn back to the other person.",
            translation: "Y tu?",
          },
        ],
      },
      {
        id: "speaking-l3-weather",
        label: "Talk About the Weather",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 3 · LESSON 2",
        title: "Small Talk — Talk About the Weather",
        description:
          "The weather is the safest small talk topic. English uses the impersonal subject \"it\" for weather.",
        objectives: [
          "Use It's + weather adjective",
          "Ask about the weather",
          "React to what the other person says",
        ],
        formulaLabel: "It's + weather word",
        formula: "It's cold today.",
        examples: [
          { source: "It's cold today.", translation: "Hace frio hoy." },
          { source: "It's raining a lot.", translation: "Esta lloviendo mucho." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk3-l2-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Weather sentences start with \"It's\", never with \"There is\".",
            prompt: "It's cold today.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "It's cold today.",
            correctAnswer: "it's cold today",
            acceptedAnswers: ["it's cold today", "it is cold today"],
            explanation: "English describes the weather with the impersonal subject it: It's cold.",
            translation: "Hace frio hoy.",
          },
          {
            id: "sk3-l2-e2",
            type: "choice",
            instruction: "Choose the correct weather sentence.",
            hint: "Weather uses \"it\" as subject, and the adjective comes right after the verb.",
            prompt: "Which sentence is correct?",
            options: ["It's sunny today.", "Is sunny today.", "Have sun today."],
            correctAnswer: "It's sunny today.",
            explanation: "The subject \"it\" cannot be omitted in English: It's sunny today.",
            translation: "Hace sol hoy.",
          },
          {
            id: "sk3-l2-e3",
            type: "speaking",
            instruction: "Say this exact question aloud.",
            hint: "Ask about the weather with \"How\" plus the verb to be.",
            prompt: "How is the weather today?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "How is the weather today?",
            correctAnswer: "how is the weather today",
            acceptedAnswers: ["how is the weather today", "how's the weather today"],
            explanation: "\"How is the weather?\" is the standard question; the contraction How's is also used.",
            translation: "Como esta el clima hoy?",
          },
        ],
      },
      {
        id: "speaking-l3-closing",
        label: "Close a Conversation",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 3 · LESSON 3",
        title: "Small Talk — Close a Conversation",
        description:
          "End a short conversation politely instead of stopping abruptly.",
        objectives: [
          "Use closing formulas like See you later",
          "Say goodbye politely",
          "Add a good wish before leaving",
        ],
        formulaLabel: "See you + time / Have a nice day",
        formula: "See you later! / Have a nice day!",
        examples: [
          { source: "See you later!", translation: "Nos vemos luego." },
          { source: "Have a nice day!", translation: "Que tengas un buen dia." },
        ],
        xpReward: 66,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk3-l3-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Three words. The subject is not used in this fixed expression.",
            prompt: "See you later!",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "See you later!",
            correctAnswer: "see you later",
            explanation: "\"See you later\" is a fixed goodbye; \"I see you later\" is not used.",
            translation: "Nos vemos luego.",
          },
          {
            id: "sk3-l3-e2",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "A good wish before leaving. It starts with the verb \"Have\".",
            prompt: "Have a nice day!",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "Have a nice day!",
            correctAnswer: "have a nice day",
            explanation: "\"Have a nice day\" is an imperative good wish, very common when leaving.",
            translation: "Que tengas un buen dia.",
          },
          {
            id: "sk3-l3-e3",
            type: "choice",
            instruction: "Choose the correct way to close a conversation at 9:00 in the morning.",
            hint: "\"Good night\" is only used late at night or before sleeping.",
            prompt: "You are leaving the office in the morning. You say:",
            options: ["Have a nice day!", "Good night!", "Nice to meet you."],
            correctAnswer: "Have a nice day!",
            explanation: "In the morning the closing wish is \"Have a nice day\". \"Good night\" would be wrong at 9 a.m.",
            translation: "Que tengas un buen dia.",
          },
        ],
      },
    ],
  },

  "speaking-l4": {
    lessonTopics: [
      {
        id: "speaking-l4-table",
        label: "Ask for a Table",
        state: "active",
        marker: "1",
        levelText: "LEVEL 4 · LESSON 1",
        title: "Restaurant — Ask for a Table",
        description:
          "Start a restaurant visit: ask for a table and say how many people are in your group.",
        objectives: [
          "Ask for a table for a number of people",
          "Use polite openings like Excuse me",
          "Answer the host's questions",
        ],
        formulaLabel: "A table for + number, please",
        formula: "A table for two, please.",
        examples: [
          { source: "A table for two, please.", translation: "Una mesa para dos, por favor." },
          { source: "Excuse me, is this table free?", translation: "Disculpe, esta libre esta mesa?" },
        ],
        xpReward: 84,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk4-l1-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Say the number as a word (two), and keep \"please\" at the end.",
            prompt: "A table for two, please.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "A table for two, please.",
            correctAnswer: "a table for two please",
            acceptedAnswers: ["a table for two please", "a table for 2 please"],
            explanation: "The pattern is \"A table for + number, please\", with the polite word at the end.",
            translation: "Una mesa para dos, por favor.",
          },
          {
            id: "sk4-l1-e2",
            type: "choice",
            instruction: "Choose the polite way to get the waiter's attention.",
            hint: "One option is polite, one is an order and one is a greeting only.",
            prompt: "You want to speak to the waiter. You say:",
            options: ["Excuse me!", "Come here!", "Good night!"],
            correctAnswer: "Excuse me!",
            explanation: "\"Excuse me\" is the polite formula to get attention. \"Come here\" sounds rude.",
            translation: "Disculpe.",
          },
          {
            id: "sk4-l1-e3",
            type: "speaking",
            instruction: "Say this exact question aloud.",
            hint: "A yes/no question with the verb to be, asking if the table is available.",
            prompt: "Is this table free?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "Is this table free?",
            correctAnswer: "is this table free",
            explanation: "The verb to be starts the yes/no question: Is this table free?",
            translation: "Esta libre esta mesa?",
          },
        ],
      },
      {
        id: "speaking-l4-order",
        label: "Order Food and Drinks",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 4 · LESSON 2",
        title: "Restaurant — Order Food and Drinks",
        description:
          "Order politely with \"I'd like\", which is softer and more natural than \"I want\".",
        objectives: [
          "Use I'd like + item",
          "Order a drink and a dish",
          "Add please to sound polite",
        ],
        formulaLabel: "I'd like + item, please",
        formula: "I'd like a sandwich, please.",
        examples: [
          { source: "I'd like a coffee, please.", translation: "Quisiera un cafe, por favor." },
          { source: "I'd like the chicken soup, please.", translation: "Quisiera la sopa de pollo, por favor." },
        ],
        xpReward: 83,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk4-l2-e1",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "\"I'd\" is the contraction of I would. Keep the article \"a\" before the item.",
            prompt: "I'd like a sandwich, please.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I'd like a sandwich, please.",
            correctAnswer: "i'd like a sandwich please",
            acceptedAnswers: ["i'd like a sandwich please", "i would like a sandwich please"],
            explanation: "\"I'd like\" (I would like) is the polite way to order.",
            translation: "Quisiera un sandwich, por favor.",
          },
          {
            id: "sk4-l2-e2",
            type: "choice",
            instruction: "Choose the most polite way to order.",
            hint: "All three are understandable, but only one is the standard polite form in a restaurant.",
            prompt: "You want a coffee. You say:",
            options: ["I'd like a coffee, please.", "Give me coffee.", "I want coffee now."],
            correctAnswer: "I'd like a coffee, please.",
            explanation: "\"I'd like ... please\" is polite; the other two sound like commands.",
            translation: "Quisiera un cafe, por favor.",
          },
          {
            id: "sk4-l2-e3",
            type: "speaking",
            instruction: "Say this exact sentence aloud.",
            hint: "Use \"the\" because you are choosing a specific dish from the menu.",
            prompt: "I'd like the chicken soup, please.",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same sentence as the prompt.",
            placeholder: "I'd like the chicken soup, please.",
            correctAnswer: "i'd like the chicken soup please",
            acceptedAnswers: ["i'd like the chicken soup please", "i would like the chicken soup please"],
            explanation: "A specific dish from the menu takes \"the\": the chicken soup.",
            translation: "Quisiera la sopa de pollo, por favor.",
          },
        ],
      },
      {
        id: "speaking-l4-bill",
        label: "Ask for the Bill",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 4 · LESSON 3",
        title: "Restaurant — Ask for the Bill",
        description:
          "Close the visit: ask for the bill, ask about payment and thank the staff.",
        objectives: [
          "Ask for the bill politely",
          "Ask if cards are accepted",
          "Thank the staff before leaving",
        ],
        formulaLabel: "Could I have + item, please?",
        formula: "Could I have the bill, please?",
        examples: [
          { source: "Could I have the bill, please?", translation: "Me trae la cuenta, por favor?" },
          { source: "Do you accept credit cards?", translation: "Aceptan tarjetas de credito?" },
        ],
        xpReward: 83,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "sk4-l3-e1",
            type: "speaking",
            instruction: "Say this exact question aloud.",
            hint: "\"Could I have\" is the polite request pattern; keep \"please\" at the end.",
            prompt: "Could I have the bill, please?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "Could I have the bill, please?",
            correctAnswer: "could i have the bill please",
            explanation: "\"Could I have ... please?\" is the standard polite request in restaurants.",
            translation: "Me trae la cuenta, por favor?",
          },
          {
            id: "sk4-l3-e2",
            type: "speaking",
            instruction: "Say this exact question aloud.",
            hint: "A simple present question with the auxiliary Do and the base verb accept.",
            prompt: "Do you accept credit cards?",
            answerLabel: "Type what you would say aloud:",
            expectedFormat: "The same question as the prompt.",
            placeholder: "Do you accept credit cards?",
            correctAnswer: "do you accept credit cards",
            explanation: "Questions with action verbs need the auxiliary do: Do you accept...?",
            translation: "Aceptan tarjetas de credito?",
          },
          {
            id: "sk4-l3-e3",
            type: "choice",
            instruction: "Choose the correct way to ask for the bill.",
            hint: "In English you ask for \"the bill\" (or \"the check\" in the US), not for \"the account\".",
            prompt: "Which sentence is correct in a restaurant?",
            options: ["Could I have the bill, please?", "Could I have the account, please?", "Could I pay the money, please?"],
            correctAnswer: "Could I have the bill, please?",
            explanation: "The restaurant document is \"the bill\" in British English and \"the check\" in American English.",
            translation: "Me trae la cuenta, por favor?",
          },
        ],
      },
    ],
  },
};
