import type { SkillContent } from "./contentTypes";

/**
 * Writing skill: every level has 3 sub-lessons with representative names.
 *
 * Open-ended writing is deliberately avoided: each typed exercise asks for one
 * specific word, connector or rewritten sentence, and the punctuation lessons
 * use `strictFormat` so capital letters and final punctuation are graded (the
 * instruction always says so).
 */
export const WRITING_CONTENT: SkillContent = {
  "writing-l1": {
    lessonTopics: [
      {
        id: "writing-l1-capitals",
        label: "Capital Letters",
        state: "active",
        marker: "1",
        levelText: "LEVEL 1 · LESSON 1",
        title: "Punctuation — Capital Letters",
        description:
          "English always capitalizes the first word of a sentence, names of people and places, days, months and the pronoun I.",
        objectives: [
          "Capitalize the first word of a sentence",
          "Capitalize names, days and months",
          "Always write the pronoun I in capital",
        ],
        formulaLabel: "Capital + sentence",
        formula: "My name is Ana.",
        examples: [
          { source: "My name is Ana.", translation: "Mi nombre es Ana." },
          { source: "I live in Quito.", translation: "Vivo en Quito." },
          { source: "We study on Monday.", translation: "Estudiamos el lunes." },
        ],
        xpReward: 34,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr1-l1-e1",
            type: "input",
            instruction: "Rewrite the sentence with correct capital letters and a final period.",
            hint: "Copy the same words in the same order. Change only two things: capitalize the first word and the name, and add the period at the end. Capital letters and punctuation ARE graded here.",
            prompt: "my name is ana",
            answerLabel: "Rewrite the full sentence:",
            expectedFormat: "Full sentence. Capital letters and the final period are graded.",
            placeholder: "My name is Ana.",
            correctAnswer: "My name is Ana.",
            strictFormat: true,
            explanation: "The first word and the personal name take a capital letter, and the statement ends with a period.",
            translation: "Mi nombre es Ana.",
          },
          {
            id: "wr1-l1-e2",
            type: "input",
            instruction: "Rewrite the sentence with correct capital letters and a final period.",
            hint: "Three changes: the first word, the pronoun i (always capital in English) and the city name. Capital letters and punctuation ARE graded.",
            prompt: "i live in quito",
            answerLabel: "Rewrite the full sentence:",
            expectedFormat: "Full sentence. Capital letters and the final period are graded.",
            placeholder: "I live in Quito.",
            correctAnswer: "I live in Quito.",
            strictFormat: true,
            explanation: "The pronoun I is always capitalized in English, and Quito is a proper noun.",
            translation: "Vivo en Quito.",
          },
          {
            id: "wr1-l1-e3",
            type: "choice",
            instruction: "Choose the sentence with correct capitalization.",
            hint: "Days of the week are capitalized in English, unlike in Spanish.",
            prompt: "Which sentence is correct?",
            options: ["We study on monday.", "We study on Monday.", "we study on Monday."],
            correctAnswer: "We study on Monday.",
            explanation: "Both the first word and the day of the week take a capital letter.",
            translation: "Estudiamos el lunes.",
          },
          {
            id: "wr1-l1-e4",
            type: "input",
            instruction: "Rewrite the sentence with correct capital letters and a final period.",
            hint: "Capitalize the first word and the month. Capital letters and punctuation ARE graded.",
            prompt: "my birthday is in july",
            answerLabel: "Rewrite the full sentence:",
            expectedFormat: "Full sentence. Capital letters and the final period are graded.",
            placeholder: "My birthday is in July.",
            correctAnswer: "My birthday is in July.",
            strictFormat: true,
            explanation: "Months are capitalized in English: July.",
            translation: "Mi cumpleanos es en julio.",
          },
        ],
      },
      {
        id: "writing-l1-end-marks",
        label: "Periods and Question Marks",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 1 · LESSON 2",
        title: "Punctuation — Periods and Question Marks",
        description:
          "Statements end with a period, questions with a question mark. English never uses an opening question mark.",
        objectives: [
          "End statements with a period",
          "End questions with a question mark",
          "Avoid the Spanish opening question mark",
        ],
        formulaLabel: "Statement. / Question?",
        formula: "She is a doctor. / Is she a doctor?",
        examples: [
          { source: "She is a doctor.", translation: "Ella es doctora." },
          { source: "Are you ready?", translation: "Estas listo?" },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr1-l2-e1",
            type: "input",
            instruction: "Rewrite the question with a capital letter and a final question mark.",
            hint: "The words do not change. Add only the capital letter at the beginning and the question mark at the end. Do NOT add an opening question mark. Punctuation IS graded.",
            prompt: "are you ready",
            answerLabel: "Rewrite the full question:",
            expectedFormat: "Full question. Capital letter and question mark are graded.",
            placeholder: "Are you ready?",
            correctAnswer: "Are you ready?",
            strictFormat: true,
            explanation: "English marks a question only at the end, with one question mark.",
            translation: "Estas listo?",
          },
          {
            id: "wr1-l2-e2",
            type: "choice",
            instruction: "Choose the correctly punctuated question.",
            hint: "Look at the beginning of each option: only one uses English punctuation.",
            prompt: "Which question is correct in English?",
            options: ["?Is she a doctor?", "Is she a doctor?", "Is she a doctor."],
            correctAnswer: "Is she a doctor?",
            explanation: "There is no opening question mark in English, and a question cannot end with a period.",
            translation: "Ella es doctora?",
          },
          {
            id: "wr1-l2-e3",
            type: "input",
            instruction: "Rewrite the statement with a capital letter and a final period.",
            hint: "Keep the same words. Add the capital letter and the period. Punctuation IS graded.",
            prompt: "she is a doctor",
            answerLabel: "Rewrite the full sentence:",
            expectedFormat: "Full sentence. Capital letter and period are graded.",
            placeholder: "She is a doctor.",
            correctAnswer: "She is a doctor.",
            strictFormat: true,
            explanation: "Statements end with a period, not with a question mark.",
            translation: "Ella es doctora.",
          },
          {
            id: "wr1-l2-e4",
            type: "choice",
            instruction: "Choose the correct end punctuation for this sentence.",
            hint: "Decide first whether the sentence asks something or states something.",
            prompt: "\"Where do you live\" needs:",
            options: ["a question mark (?)", "a period (.)", "no punctuation"],
            correctAnswer: "a question mark (?)",
            explanation: "\"Where do you live\" is a question, so it ends with a question mark.",
            translation: "Donde vives?",
          },
        ],
      },
      {
        id: "writing-l1-commas",
        label: "Commas in Lists",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 1 · LESSON 3",
        title: "Punctuation — Commas in Lists",
        description:
          "In a list, items are separated by commas and the last one is joined with \"and\".",
        objectives: [
          "Separate list items with commas",
          "Join the last item with and",
          "Avoid a comma before the verb",
        ],
        formulaLabel: "A, B and C",
        formula: "I have a pen, a book and a bag.",
        examples: [
          { source: "I have a pen, a book and a bag.", translation: "Tengo un boligrafo, un libro y una mochila." },
          { source: "We study English, math and history.", translation: "Estudiamos ingles, matematicas e historia." },
        ],
        xpReward: 33,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr1-l3-e1",
            type: "choice",
            instruction: "Choose the correctly punctuated list.",
            hint: "Commas separate the first items and \"and\" joins the last one. No comma goes right before the verb.",
            prompt: "Which sentence is correct?",
            options: [
              "I have a pen, a book and a bag.",
              "I have a pen a book and a bag.",
              "I have, a pen, a book and a bag.",
            ],
            correctAnswer: "I have a pen, a book and a bag.",
            explanation: "The comma separates list items; it never goes between the verb and its object.",
            translation: "Tengo un boligrafo, un libro y una mochila.",
          },
          {
            id: "wr1-l3-e2",
            type: "input",
            instruction: "Write the word that joins the last item of a list.",
            hint: "Write ONE word: the conjunction used before the final item of any list.",
            prompt: "We study English, math _____ history.",
            answerLabel: "Write the connector:",
            expectedFormat: "One word.",
            placeholder: "one word...",
            correctAnswer: "and",
            explanation: "The last item of a list is joined with \"and\", not with another comma.",
            translation: "Estudiamos ingles, matematicas e historia.",
          },
          {
            id: "wr1-l3-e3",
            type: "reorder",
            instruction: "Build the list sentence using every block once.",
            hint: "The blocks already include their commas. Start with the subject and verb, then the items in order.",
            prompt: "I like / apples, / bananas / and oranges",
            options: ["I like", "apples,", "bananas", "and oranges"],
            correctAnswer: "i like apples, bananas and oranges",
            explanation: "Order: subject + verb + item, item + and + last item.",
            translation: "Me gustan las manzanas, los platanos y las naranjas.",
          },
          {
            id: "wr1-l3-e4",
            type: "choice",
            instruction: "Choose the list with the comma in the right place.",
            hint: "Only items are separated; the verb stays attached to the sentence.",
            prompt: "Which sentence is correct?",
            options: [
              "She speaks Spanish, English and French.",
              "She speaks, Spanish English and French.",
              "She speaks Spanish English, and French.",
            ],
            correctAnswer: "She speaks Spanish, English and French.",
            explanation: "The comma goes between the listed languages, never after the verb.",
            translation: "Ella habla espanol, ingles y frances.",
          },
        ],
      },
    ],
  },

  "writing-l2": {
    lessonTopics: [
      {
        id: "writing-l2-opening",
        label: "Greeting and Subject",
        state: "active",
        marker: "1",
        levelText: "LEVEL 2 · LESSON 1",
        title: "Emails — Greeting and Subject",
        description:
          "Open an email with a clear subject line and an appropriate greeting for the situation.",
        objectives: [
          "Write a short, specific subject line",
          "Choose a formal or informal greeting",
          "Use a comma after the greeting",
        ],
        formulaLabel: "Dear + name, / Hi + name,",
        formula: "Dear Mr. Lopez, / Hi Ana,",
        examples: [
          { source: "Dear Mr. Lopez,", translation: "Estimado Sr. Lopez," },
          { source: "Hi Ana,", translation: "Hola Ana," },
          { source: "Subject: Request for information", translation: "Asunto: Solicitud de informacion" },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr2-l1-e1",
            type: "choice",
            instruction: "Choose the correct greeting for a formal email to a manager you do not know.",
            hint: "Formal emails use \"Dear\" plus the family name; informal ones use \"Hi\" plus the first name.",
            prompt: "You are writing to Mr. Lopez, a manager. You start with:",
            options: ["Dear Mr. Lopez,", "Hey Lopez!", "Hello you,"],
            correctAnswer: "Dear Mr. Lopez,",
            explanation: "\"Dear + title + family name\" is the standard formal greeting, followed by a comma.",
            translation: "Estimado Sr. Lopez,",
          },
          {
            id: "wr2-l1-e2",
            type: "input",
            instruction: "Write the missing word of the formal greeting.",
            hint: "Write ONE word: the adjective used at the beginning of a formal English email, before the name.",
            prompt: "_____ Ms. Perez, thank you for your message.",
            answerLabel: "Write the greeting word:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one word...",
            correctAnswer: "dear",
            explanation: "Formal emails start with \"Dear\", never with \"Hello you\" or \"Hey\".",
            translation: "Estimada Sra. Perez, gracias por su mensaje.",
          },
          {
            id: "wr2-l1-e3",
            type: "choice",
            instruction: "Choose the most useful subject line.",
            hint: "A good subject line names the topic in a few words; it is not a greeting and it is not empty.",
            prompt: "You are asking about course prices. Your subject line is:",
            options: ["Request for course prices", "Hello!", "Information"],
            correctAnswer: "Request for course prices",
            explanation: "The subject must state the topic clearly. \"Hello!\" and \"Information\" say nothing about the content.",
            translation: "Solicitud de precios de cursos",
          },
          {
            id: "wr2-l1-e4",
            type: "reorder",
            instruction: "Build the first line of the email using every block once.",
            hint: "Greeting first (with its comma), then the thanks, then the object.",
            prompt: "Dear Ms. Perez, / thank you / for your email",
            options: ["Dear Ms. Perez,", "thank you", "for your email"],
            correctAnswer: "dear ms. perez, thank you for your email",
            explanation: "The greeting opens the email and the first sentence acknowledges the previous message.",
            translation: "Estimada Sra. Perez, gracias por su correo.",
          },
        ],
      },
      {
        id: "writing-l2-requests",
        label: "Polite Requests",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 2 · LESSON 2",
        title: "Emails — Polite Requests",
        description:
          "Ask for something without sounding demanding: \"I'd like\", \"Could you\" and \"Would it be possible to\".",
        objectives: [
          "Replace I want with I'd like",
          "Ask with Could you + base verb",
          "Add please in the right position",
        ],
        formulaLabel: "Could you + base verb + please?",
        formula: "Could you send me the price list, please?",
        examples: [
          { source: "I'd like more information.", translation: "Me gustaria mas informacion." },
          { source: "Could you send me the price list?", translation: "Podria enviarme la lista de precios?" },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr2-l2-e1",
            type: "input",
            instruction: "Rewrite \"I want information.\" as a polite request.",
            hint: "Replace \"want\" with the polite form \"would like\" using the contraction: I'd like. Keep the same noun and the final period.",
            prompt: "I want information.",
            answerLabel: "Rewrite the sentence politely:",
            expectedFormat: "Full sentence. \"I would like information.\" is also accepted.",
            placeholder: "I'd like information.",
            correctAnswer: "i'd like information",
            acceptedAnswers: ["i'd like information", "i would like information"],
            explanation: "\"I'd like\" is the polite equivalent of \"I want\" in written English.",
            translation: "Me gustaria informacion.",
          },
          {
            id: "wr2-l2-e2",
            type: "choice",
            instruction: "Choose the most polite request.",
            hint: "Polite requests are questions with a modal verb, not imperatives.",
            prompt: "You need the price list. You write:",
            options: [
              "Could you send me the price list, please?",
              "Send me the price list.",
              "I need the price list now.",
            ],
            correctAnswer: "Could you send me the price list, please?",
            explanation: "\"Could you ... please?\" turns the request into a polite question.",
            translation: "Podria enviarme la lista de precios, por favor?",
          },
          {
            id: "wr2-l2-e3",
            type: "input",
            instruction: "Write the modal verb that makes the request polite.",
            hint: "Write ONE word: the past form of \"can\" used for polite requests.",
            prompt: "_____ you send me the document, please?",
            answerLabel: "Write the modal verb:",
            expectedFormat: "One word. \"Would\" is also accepted.",
            placeholder: "one word...",
            correctAnswer: "could",
            acceptedAnswers: ["could", "would"],
            explanation: "\"Could\" (or \"Would\") makes a request more polite than \"Can\".",
            translation: "Podria enviarme el documento, por favor?",
          },
          {
            id: "wr2-l2-e4",
            type: "reorder",
            instruction: "Build the polite request using every block once.",
            hint: "Order: modal + subject + base verb + object + please.",
            prompt: "confirm / Could you / the date / please?",
            options: ["Could you", "confirm", "the date", "please?"],
            correctAnswer: "could you confirm the date please?",
            explanation: "The modal opens the question and \"please\" closes it.",
            translation: "Podria confirmar la fecha, por favor?",
          },
        ],
      },
      {
        id: "writing-l2-closing",
        label: "Closing an Email",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 2 · LESSON 3",
        title: "Emails — Closing an Email",
        description:
          "Close the message with a short courtesy sentence and a standard sign-off before your name.",
        objectives: [
          "Write a closing courtesy sentence",
          "Choose a formal or informal sign-off",
          "Place your name after the sign-off",
        ],
        formulaLabel: "Courtesy + sign-off + name",
        formula: "Thank you. Best regards, Mateo",
        examples: [
          { source: "Thank you for your help.", translation: "Gracias por su ayuda." },
          { source: "Best regards, Mateo", translation: "Saludos cordiales, Mateo" },
        ],
        xpReward: 50,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr2-l3-e1",
            type: "choice",
            instruction: "Choose the correct sign-off for a formal email.",
            hint: "Formal sign-offs are fixed expressions followed by a comma and your name.",
            prompt: "You are ending a formal email. You write:",
            options: ["Best regards,", "Bye bye!", "That's all."],
            correctAnswer: "Best regards,",
            explanation: "\"Best regards,\" is a standard formal sign-off. The others are too informal or incomplete.",
            translation: "Saludos cordiales,",
          },
          {
            id: "wr2-l3-e2",
            type: "input",
            instruction: "Write the missing word of the closing courtesy sentence.",
            hint: "Write ONE word: the verb used to thank someone, at the beginning of the sentence.",
            prompt: "_____ you for your help.",
            answerLabel: "Write the missing word:",
            expectedFormat: "One word.",
            placeholder: "one word...",
            correctAnswer: "thank",
            explanation: "\"Thank you for + noun\" is the standard courtesy closing.",
            translation: "Gracias por su ayuda.",
          },
          {
            id: "wr2-l3-e3",
            type: "reorder",
            instruction: "Build the closing using every block once.",
            hint: "Order: courtesy sentence, then sign-off, then your name.",
            prompt: "Best regards, / Thank you for your time. / Mateo",
            options: ["Thank you for your time.", "Best regards,", "Mateo"],
            correctAnswer: "thank you for your time. best regards, mateo",
            explanation: "An email closes with the courtesy sentence, the sign-off and the sender's name.",
            translation: "Gracias por su tiempo. Saludos cordiales, Mateo",
          },
          {
            id: "wr2-l3-e4",
            type: "choice",
            instruction: "Choose the correct order of the closing elements.",
            hint: "The name always comes last, after the sign-off.",
            prompt: "Which order is correct?",
            options: [
              "Thank you. Best regards, Ana",
              "Ana, Best regards. Thank you",
              "Best regards, Thank you Ana",
            ],
            correctAnswer: "Thank you. Best regards, Ana",
            explanation: "Courtesy sentence, then sign-off with a comma, then the name.",
            translation: "Gracias. Saludos cordiales, Ana",
          },
        ],
      },
    ],
  },

  "writing-l3": {
    lessonTopics: [
      {
        id: "writing-l3-opinion",
        label: "State Your Opinion",
        state: "active",
        marker: "1",
        levelText: "LEVEL 3 · LESSON 1",
        title: "Paragraphs — State Your Opinion",
        description:
          "Open an argumentative paragraph with a clear opinion sentence: \"I think (that) + subject + verb\".",
        objectives: [
          "Open with I think / In my opinion",
          "Write a complete opinion sentence",
          "Avoid starting with the reason",
        ],
        formulaLabel: "I think + subject + verb",
        formula: "I think English is useful.",
        examples: [
          { source: "I think English is useful.", translation: "Creo que el ingles es util." },
          { source: "In my opinion, reading is important.", translation: "En mi opinion, leer es importante." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr3-l1-e1",
            type: "input",
            instruction: "Write the verb that introduces a personal opinion.",
            hint: "Write ONE word: the verb used after \"I\" to express an opinion (it is not \"believe\" in this pattern).",
            prompt: "I _____ English is useful.",
            answerLabel: "Write the verb:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "think",
            acceptedAnswers: ["think", "believe"],
            explanation: "\"I think + sentence\" is the most common way to introduce an opinion in English.",
            translation: "Creo que el ingles es util.",
          },
          {
            id: "wr3-l1-e2",
            type: "choice",
            instruction: "Choose the complete opinion sentence.",
            hint: "After \"I think\" you need a full sentence with its own subject and verb.",
            prompt: "Which sentence is correct?",
            options: [
              "I think English is useful.",
              "I think English useful.",
              "I think that useful English.",
            ],
            correctAnswer: "I think English is useful.",
            explanation: "The opinion clause needs a subject (English) and a verb (is).",
            translation: "Creo que el ingles es util.",
          },
          {
            id: "wr3-l1-e3",
            type: "reorder",
            instruction: "Build the opinion sentence using every block once.",
            hint: "Order: opinion phrase (with its comma), then subject, then verb, then adjective.",
            prompt: "important / In my opinion, / reading / is",
            options: ["In my opinion,", "reading", "is", "important"],
            correctAnswer: "in my opinion, reading is important",
            explanation: "\"In my opinion,\" opens the sentence and is followed by a complete clause.",
            translation: "En mi opinion, leer es importante.",
          },
          {
            id: "wr3-l1-e4",
            type: "choice",
            instruction: "Choose the sentence that belongs at the beginning of an argumentative paragraph.",
            hint: "The first sentence states the position; reasons and examples come afterwards.",
            prompt: "Which sentence opens the paragraph?",
            options: [
              "I think online classes are useful.",
              "For example, my cousin studies online.",
              "Because it saves time.",
            ],
            correctAnswer: "I think online classes are useful.",
            explanation: "The opening sentence gives the opinion. The other two are support and cannot stand first.",
            translation: "Creo que las clases en linea son utiles.",
          },
        ],
      },
      {
        id: "writing-l3-reasons",
        label: "Give a Reason with because",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 3 · LESSON 2",
        title: "Paragraphs — Give a Reason with because",
        description:
          "Support your opinion with one reason introduced by \"because\", followed by a complete clause.",
        objectives: [
          "Join opinion and reason with because",
          "Write a complete clause after because",
          "Avoid using because alone as a sentence",
        ],
        formulaLabel: "Opinion + because + reason",
        formula: "I think it is useful because it saves time.",
        examples: [
          {
            source: "I think English is useful because it helps me communicate.",
            translation: "Creo que el ingles es util porque me ayuda a comunicarme.",
          },
          { source: "I like reading because it improves my vocabulary.", translation: "Me gusta leer porque mejora mi vocabulario." },
        ],
        xpReward: 67,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr3-l2-e1",
            type: "input",
            instruction: "Write the connector that introduces a reason.",
            hint: "Write ONE word: the connector that means \"porque\" and is followed by subject + verb.",
            prompt: "I like reading _____ it improves my vocabulary.",
            answerLabel: "Write the connector:",
            expectedFormat: "One word.",
            placeholder: "one connector...",
            correctAnswer: "because",
            explanation: "\"Because\" introduces the reason and is followed by a complete clause.",
            translation: "Me gusta leer porque mejora mi vocabulario.",
          },
          {
            id: "wr3-l2-e2",
            type: "choice",
            instruction: "Choose the correct clause after \"because\".",
            hint: "After \"because\" you need a subject and a verb, not just a noun.",
            prompt: "I study English because _____",
            options: ["it helps me at work.", "for my work.", "helping at work."],
            correctAnswer: "it helps me at work.",
            explanation: "Only the first option has a subject (it) and a verb (helps).",
            translation: "Estudio ingles porque me ayuda en el trabajo.",
          },
          {
            id: "wr3-l2-e3",
            type: "reorder",
            instruction: "Build the opinion + reason sentence using every block once.",
            hint: "Opinion first, then the connector, then the reason clause.",
            prompt: "because it saves time / I think / online classes are useful",
            options: ["I think", "online classes are useful", "because it saves time"],
            correctAnswer: "i think online classes are useful because it saves time",
            explanation: "The reason always comes after the opinion when it is introduced by \"because\".",
            translation: "Creo que las clases en linea son utiles porque ahorran tiempo.",
          },
          {
            id: "wr3-l2-e4",
            type: "choice",
            instruction: "Choose the correctly written sentence.",
            hint: "\"Because\" cannot form a sentence by itself; it must be attached to the main idea.",
            prompt: "Which option is correct in a paragraph?",
            options: [
              "I like this city because it is quiet.",
              "I like this city. Because it is quiet.",
              "Because it is quiet. I like this city.",
            ],
            correctAnswer: "I like this city because it is quiet.",
            explanation: "The reason clause is joined to the main clause in one sentence.",
            translation: "Me gusta esta ciudad porque es tranquila.",
          },
        ],
      },
      {
        id: "writing-l3-connectors",
        label: "Add a Second Idea",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 3 · LESSON 3",
        title: "Paragraphs — Add a Second Idea",
        description:
          "Extend the paragraph with \"also\" to add an idea and \"however\" to introduce a contrast.",
        objectives: [
          "Add a second reason with also",
          "Introduce a contrast with however",
          "Choose the connector by its meaning",
        ],
        formulaLabel: "also (adds) / however (contrasts)",
        formula: "It is cheap. However, it is slow.",
        examples: [
          { source: "It is also cheaper than a course.", translation: "Tambien es mas barato que un curso." },
          { source: "However, it needs discipline.", translation: "Sin embargo, requiere disciplina." },
        ],
        xpReward: 66,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "wr3-l3-e1",
            type: "choice",
            instruction: "Choose the connector that adds a similar idea.",
            hint: "The second sentence agrees with the first, so you need an addition connector, not a contrast one.",
            prompt: "Online classes save time. They are _____ cheaper.",
            options: ["also", "however", "but"],
            correctAnswer: "also",
            explanation: "\"Also\" adds a second idea in the same direction. \"However\" and \"but\" introduce contrast.",
            translation: "Las clases en linea ahorran tiempo. Tambien son mas baratas.",
          },
          {
            id: "wr3-l3-e2",
            type: "input",
            instruction: "Write the connector that introduces a contrast.",
            hint: "Write ONE word: the formal connector that means \"sin embargo\" and is followed by a comma.",
            prompt: "Online classes are cheap. _____ , they need discipline.",
            answerLabel: "Write the connector:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one connector...",
            correctAnswer: "however",
            explanation: "\"However\" introduces an opposite idea and is followed by a comma in written English.",
            translation: "Las clases en linea son baratas. Sin embargo, requieren disciplina.",
          },
          {
            id: "wr3-l3-e3",
            type: "choice",
            instruction: "Choose the connector that fits the meaning.",
            hint: "Read both ideas: the second one is a disadvantage, so it contrasts with the first.",
            prompt: "The app is free. _____ , it has advertisements.",
            options: ["However", "Also", "Because"],
            correctAnswer: "However",
            explanation: "Being free is positive and having advertisements is negative, so the relation is contrast.",
            translation: "La aplicacion es gratis. Sin embargo, tiene publicidad.",
          },
          {
            id: "wr3-l3-e4",
            type: "reorder",
            instruction: "Build the sentence using every block once.",
            hint: "The connector \"also\" goes between the verb and the adjective.",
            prompt: "also / It is / useful for work",
            options: ["It is", "also", "useful for work"],
            correctAnswer: "it is also useful for work",
            explanation: "With the verb to be, \"also\" goes right after the verb: It is also useful.",
            translation: "Tambien es util para el trabajo.",
          },
        ],
      },
    ],
  },

  "writing-l4": {
    lessonTopics: [
      {
        id: "writing-l4-sequence",
        label: "Sequence Words",
        state: "active",
        marker: "1",
        levelText: "LEVEL 4 · LESSON 1",
        title: "Storytelling — Sequence Words",
        description:
          "Order the events of a story with first, then, after that and finally.",
        objectives: [
          "Use first, then and finally",
          "Keep the events in chronological order",
          "Place the sequence word at the beginning",
        ],
        formulaLabel: "First ... then ... finally ...",
        formula: "First I woke up, then I had breakfast.",
        examples: [
          {
            source: "First I woke up, then I had breakfast.",
            translation: "Primero me desperte, luego desayune.",
          },
          { source: "Finally, I went to school.", translation: "Finalmente, fui a la escuela." },
        ],
        xpReward: 84,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr4-l1-e1",
            type: "input",
            instruction: "Write the sequence word that introduces the first event.",
            hint: "Write ONE word: the sequence word used for the first action of a story.",
            prompt: "_____ , I woke up at six.",
            answerLabel: "Write the sequence word:",
            expectedFormat: "One word. Capital letters are not graded.",
            placeholder: "one word...",
            correctAnswer: "first",
            explanation: "\"First\" marks the first event of the sequence.",
            translation: "Primero, me desperte a las seis.",
          },
          {
            id: "wr4-l1-e2",
            type: "choice",
            instruction: "Choose the sequence word for the last event.",
            hint: "The sentence closes the story, so you need the word that marks the end.",
            prompt: "_____ , I went to bed.",
            options: ["Finally", "First", "Then"],
            correctAnswer: "Finally",
            explanation: "\"Finally\" marks the last event. \"First\" and \"then\" are used earlier in the sequence.",
            translation: "Finalmente, me fui a dormir.",
          },
          {
            id: "wr4-l1-e3",
            type: "reorder",
            instruction: "Build the sentence using every block once.",
            hint: "Keep the chronological order given by the sequence words: first, then.",
            prompt: "then I had breakfast / First I woke up,",
            options: ["First I woke up,", "then I had breakfast"],
            correctAnswer: "first i woke up, then i had breakfast",
            explanation: "The sequence word determines the order: first comes before then.",
            translation: "Primero me desperte, luego desayune.",
          },
          {
            id: "wr4-l1-e4",
            type: "choice",
            instruction: "Choose the correctly ordered story.",
            hint: "Check whether the events follow a logical time order.",
            prompt: "Which order makes sense?",
            options: [
              "First I studied, then I took the exam.",
              "First I took the exam, then I studied.",
              "Finally I studied, first I took the exam.",
            ],
            correctAnswer: "First I studied, then I took the exam.",
            explanation: "Studying happens before the exam, so it takes \"first\".",
            translation: "Primero estudie, luego hice el examen.",
          },
        ],
      },
      {
        id: "writing-l4-past-narration",
        label: "Past Tense Narration",
        state: "blocked",
        marker: "2",
        levelText: "LEVEL 4 · LESSON 2",
        title: "Storytelling — Past Tense Narration",
        description:
          "Stories about finished events are written in the simple past, keeping the same tense from beginning to end.",
        objectives: [
          "Write narrative sentences in the simple past",
          "Keep the same tense in the whole story",
          "Use irregular past forms correctly",
        ],
        formulaLabel: "Subject + past verb",
        formula: "I woke up early.",
        examples: [
          { source: "I woke up early and went out.", translation: "Me desperte temprano y sali." },
          { source: "We walked to the park.", translation: "Caminamos al parque." },
        ],
        xpReward: 83,
        minutesLabel: "~3 mins",
        exercises: [
          {
            id: "wr4-l2-e1",
            type: "reorder",
            instruction: "Build the past sentence using every word once.",
            hint: "Order: subject + past verb + adverb. The verb block is already in the past.",
            prompt: "woke up / I / early",
            options: ["I", "woke up", "early"],
            correctAnswer: "i woke up early",
            explanation: "The narrative order is subject + past verb + complement: I woke up early.",
            translation: "Me desperte temprano.",
          },
          {
            id: "wr4-l2-e2",
            type: "input",
            instruction: "Write the past form of the verb \"walk\".",
            hint: "Write ONE word. \"Walk\" is a regular verb, so it takes -ed.",
            prompt: "We _____ to the park. (walk)",
            answerLabel: "Write the past form:",
            expectedFormat: "One word ending in -ed.",
            placeholder: "verb + ed...",
            correctAnswer: "walked",
            explanation: "Regular verbs form the past with -ed: walk -> walked.",
            translation: "Caminamos al parque.",
          },
          {
            id: "wr4-l2-e3",
            type: "choice",
            instruction: "Choose the sentence that keeps the story in the past.",
            hint: "All verbs of a finished story must be in the same tense.",
            prompt: "Which sentence continues \"Yesterday I woke up early...\"?",
            options: [
              "...and I had breakfast with my family.",
              "...and I have breakfast with my family.",
              "...and I am having breakfast with my family.",
            ],
            correctAnswer: "...and I had breakfast with my family.",
            explanation: "The story is in the past, so the second verb must also be past: had.",
            translation: "...y desayune con mi familia.",
          },
          {
            id: "wr4-l2-e4",
            type: "input",
            instruction: "Write the past form of the verb \"go\".",
            hint: "Write ONE word. \"Go\" is irregular: it does not take -ed.",
            prompt: "After that, I _____ to school. (go)",
            answerLabel: "Write the past form:",
            expectedFormat: "One word.",
            placeholder: "one verb...",
            correctAnswer: "went",
            explanation: "The past of go is went, for every subject.",
            translation: "Despues de eso, fui a la escuela.",
          },
        ],
      },
      {
        id: "writing-l4-details",
        label: "Adding Details",
        state: "blocked",
        marker: "3",
        levelText: "LEVEL 4 · LESSON 3",
        title: "Storytelling — Adding Details",
        description:
          "Make a story more interesting by adding when, where and how the events happened.",
        objectives: [
          "Add time expressions to the events",
          "Add place expressions",
          "Place details at the end of the sentence",
        ],
        formulaLabel: "Event + place + time",
        formula: "I met her at the park yesterday.",
        examples: [
          { source: "I met her at the park yesterday.", translation: "La encontre en el parque ayer." },
          { source: "We arrived home very late.", translation: "Llegamos a casa muy tarde." },
        ],
        xpReward: 83,
        minutesLabel: "~4 mins",
        exercises: [
          {
            id: "wr4-l3-e1",
            type: "reorder",
            instruction: "Build the sentence using every block once.",
            hint: "English order for details: action first, then place, then time.",
            prompt: "yesterday / I met her / at the park",
            options: ["I met her", "at the park", "yesterday"],
            correctAnswer: "i met her at the park yesterday",
            explanation: "Place comes before time in English: at the park (place) + yesterday (time).",
            translation: "La encontre en el parque ayer.",
          },
          {
            id: "wr4-l3-e2",
            type: "choice",
            instruction: "Choose the sentence with the details in the correct order.",
            hint: "Place normally comes before time in an English sentence.",
            prompt: "Which sentence is correct?",
            options: [
              "We studied at the library last night.",
              "We studied last night at the library.",
              "We at the library studied last night.",
            ],
            correctAnswer: "We studied at the library last night.",
            explanation: "The standard order is verb + place + time. The second option is possible but less natural, and the third is incorrect.",
            translation: "Estudiamos en la biblioteca anoche.",
          },
          {
            id: "wr4-l3-e3",
            type: "input",
            instruction: "Write the preposition that goes before a specific place.",
            hint: "Write ONE word: the preposition used before places like \"the park\" or \"the library\".",
            prompt: "I met my friends _____ the park.",
            answerLabel: "Write the preposition:",
            expectedFormat: "One word.",
            placeholder: "one preposition...",
            correctAnswer: "at",
            acceptedAnswers: ["at", "in"],
            explanation: "\"At\" is used for a specific location: at the park, at the library.",
            translation: "Encontre a mis amigos en el parque.",
          },
          {
            id: "wr4-l3-e4",
            type: "reorder",
            instruction: "Build the sentence using every block once.",
            hint: "Action first, then the manner detail at the end.",
            prompt: "very late / We arrived / home",
            options: ["We arrived", "home", "very late"],
            correctAnswer: "we arrived home very late",
            explanation: "\"Home\" needs no preposition after arrive, and the time detail closes the sentence.",
            translation: "Llegamos a casa muy tarde.",
          },
        ],
      },
    ],
  },
};
